### ISSUE TITLE
Add a \label tag option for LaTeX output (work around provided)

### ISSUE THREAD

**Issue by NicholasWMRitchie** [ronisbr/PrettyTables.jl#103]
In LaTeX it is common to identify tables with a "\label{tbl:thistabel}" where the label can be referenced in the text as "\ref{tbl:thislabel}".  This is the default mechanism to number tables and then reference the numbers in the text.

It is possible to hack the current `title` argument to include a label like this...

    title = """
       This is my title.}
       \label{tbl:thistable"""

Note: I include the closing "}" on the title but not on the "\label{".

An additional named argument `label = "tbl:thistable"` would be much clearer than the current hack.

**Comment by ronisbr** [comment]
Hi @NicholasWMRitchie ,

Sure, we can add a keyword `label` to the LaTeX back-end. It should be very easy.

**Comment by ronisbr** [comment]
@NicholasWMRitchie done! Can you please test using `master`?

**Comment by NicholasWMRitchie** [comment]
Thanks so much for implementing this!  I did notice one problem.  The \label{} tag must go after the \caption{} tag or it can be assigned the wrong number when referenced in the text.  Typically, the \label{} tag is placed as the last item in the `table` or `longtable` environment (right before the \end{table} or \end{longtable})

**Comment by NicholasWMRitchie** [comment]
It took me a while to find somewhere that explicitly stated the required relationship between \label and \caption.  While not a primary source, [this site](https://www.stefaanlippens.net/latexcaptionlabel/) is consistent with my experience.

**Comment by ronisbr** [comment]
Done! Can you test please?

**Comment by NicholasWMRitchie** [comment]
👍 This new code produces the correct reference numbers in my test document.  
Thanks!
