### ISSUE TITLE
Reexport compat bound issue?

### ISSUE THREAD

**Issue by thchr** [ronisbr/PrettyTables.jl#105]
I've been getting errors on CI for a week or two that are related to PrettyTables (e.g. [this log](https://github.com/thchr/Crystalline.jl/runs/1645198579?check_suite_focus=true)). I looked into it today, and I realized that the build step is pulling in PrettyTables at version 0.1.0 rather than its most recent. I believe this is due to a compat conflict after a recent versioning update of Reexport.jl over in https://github.com/simonster/Reexport.jl/pull/23.

Currently, the compat entry in PrettyTables.jl is set to 0.2.0; maybe it should just be pulled up to 1.0.0? If you agree, I can make a PR (it would be nice to fix; I think this could break a good deal of CI for packages that depend on PrettyTables).

[I'm honestly not completely sure if the compat entry here is to blame; for instance, my test CI works fine with PrettyTables, but only breaks when combined with Documenter.jl; there's some conflict that that is causing PrettyTables.jl to be downgraded.]

**Comment by nalimilan** [comment]
If your package doesn't work with older PrettyTables versions, why not add a lower bounds to Compat.toml? At least that will make the dependency error happen earlier.

Allowing PrettyTables to use Requires 1.0 is a good idea anyway.

**Comment by thchr** [comment]
> If your package doesn't work with older PrettyTables versions, why not add a lower bounds to Project.toml? At least that will make the dependency error happen earlier.

This is a good point; I will do that..!
