### ISSUE TITLE
Booktabs for LaTeX backend

### ISSUE THREAD

**Issue by jolars** [ronisbr/PrettyTables.jl#108]
Please consider allowing [booktabs](https://www.ctan.org/pkg/booktabs) for the latex backend, using `\toprule`, `\midrule`, and `\bottomrule` instead of `\hline`.

It should be relatively easy option to include and should probably also use single rules instead of the current default double rules to comply with the style intended by the booktabs package.

**Comment by ronisbr** [comment]
Hi @jolars ! I think it is already implemented as you want. Just try to pass the parameter `tf = tf_latex_booktabs`. Please, tell me if it worked.

**Comment by jolars** [comment]
Sorry! I failed to check the development version. Apologies! Great to see that you've included this.
