### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devmotion** [ronisbr/PrettyTables.jl#109]
I noticed that the master branch is already compatible with Reexport 1 but it has not been released. Is it possible to make a new release with the updated compatibilities? It would allow us to test and then possibly release new versions of MCMCChains, Turing, and AbstractGPs that are currently blocked by PrettyTables :slightly_smiling_face:

**Comment by ronisbr** [comment]
Hi @devmotion 

Yes, sorry about that. I am very busy with things related to my work and did not have time yet to do so. I promise it will be done by this weekend :)

**Comment by ronisbr** [comment]
I just ask for registration :) Should be available soon.

**Comment by devmotion** [comment]
Thanks a lot! 🙂
