### ISSUE TITLE
Misaligned table in Literate/documentation

### ISSUE THREAD

**Issue by charleskawczynski** [ronisbr/PrettyTables.jl#111]
It's a bit much to make an MWE, but using 

```julia
using PrettyTables

eqs = SubString{String}["X", "Y"]

data = AbstractString["X" "(F1)" "()" "(S1, S2)"; "Y" "(F1)" "(FY2)" "(S1, S2)"]

header = [
    "Equation" "Flux{FirstOrder}" "Flux{SecondOrder}" "Source"
    "(Y_i)" "(F_1)" "(F_2)" "(S)"
]

pretty_table(
    data,
    header;
    header_crayon = crayon"yellow bold",
    subheader_crayon = crayon"green bold",
    crop = :none,
)
```
in a [Literate.jl](https://github.com/fredrikekre/Literate.jl) example, from what I can tell, results in a misaligned table:

![BadTable](https://user-images.githubusercontent.com/1880641/107171416-95c9ff00-6977-11eb-83ce-4bc93098e703.png)

In the REPL, things look fine:

![GoodTable](https://user-images.githubusercontent.com/1880641/107171496-cc077e80-6977-11eb-80b2-15c74840ca9e.png)

I'll try to narrow down the issue if possible, but I just want to record this for now.

**Comment by ronisbr** [comment]
Hi @charleskawczynski 

Are you sure this is not a problem with the software used to open the file? It seems you are using a font that is not monospaced.

I copied your example and executed:

```julia
julia> Literate.markdown("teste.jl", "."; documenter = false, execute = true)
```

The result was:

<img width="740" alt="Captura de Tela 2021-02-09 às 11 26 53" src="https://user-images.githubusercontent.com/1068295/107377421-b6a26980-6ac9-11eb-8e1d-163cf368ea69.png">

**Comment by charleskawczynski** [comment]
Yeah, the example is being incorporated into docs, not just run in the REPL. I'm probably not capturing the conditions that lead to this. I'll try to update with something more precise.

**Comment by ronisbr** [comment]
Maybe you are seeing a text table being rendered in a browser without a monospaced font?

**Comment by charleskawczynski** [comment]
I'm not sure I understand what you mean. What I saw was rendered using Documenter.jl/Literate.jl, in Chrome.

**Comment by ronisbr** [comment]
Can you please copy the text rendered by Chrome and paste in a text editor like Vim / Emacs / Visual Code / etc?

**Comment by charleskawczynski** [comment]
Working on it in [this PR](https://github.com/CliMA/ClimateMachine.jl/pull/2041). I'll post a link to the docs once it's generated.

**Comment by charleskawczynski** [comment]
Weird. I can no longer reproduce this 🤷🏻‍♂️. Here's a screenshot of my attempt:

<img width="829" alt="Screen Shot 2021-02-16 at 3 52 25 PM" src="https://user-images.githubusercontent.com/1880641/108136504-060b0b80-706f-11eb-8d24-bba182c71c19.png">

Not that I would expect anything different, here's what I get when copying the text:
```julia
PDE: ∂_t Y_i + (∇•F_1(Y))_i + (∇•F_2(Y,G)))_i = (S(Y,G))_i
┌──────────┬──────────────────┬───────────────────┬────────────────────┐
│ Equation │ Flux{FirstOrder} │ Flux{SecondOrder} │             Source │
│    (Y_i) │            (F_1) │             (F_2) │                (S) │
├──────────┼──────────────────┼───────────────────┼────────────────────┤
│        X │      (Advection) │                () │ (Source1, Source2) │
│        Y │      (Advection) │       (Diffusion) │ (Source1, Source2) │
└──────────┴──────────────────┴───────────────────┴────────────────────┘
```

but this is from the table whose screenshot looks fine. @ronisbr sorry I didn't copy the text the first time over. I guess I'm okay with closing.

**Comment by charleskawczynski** [comment]
Aaaand I see the [misalignment](https://clima.github.io/ClimateMachine.jl/latest/generated/BalanceLaws/tendency_specification_layer/#Testing-prognostic_vars-eq_tends) again.

**Comment by ronisbr** [comment]
Can you please see if this happens in terminal? I am pretty sure that it is not related to PrettyTables. In this case, there isn’t any additional characters causing the misalignment. If you paste the text in a terminal, you will see that it is perfectly aligned.

**Comment by charleskawczynski** [comment]
Ah, I completely agree. Closing. Any idea where we should open an issue? Shouldn't code blocks be mono-spaced?

**Comment by ronisbr** [comment]
No problem! It seems for me the font selection in HTML. Are you using Documenter.jl to create those pages?

**Comment by charleskawczynski** [comment]
> Are you using Documenter.jl to create those pages?
Yep

The html font is selected in Documenter.jl?

**Comment by ronisbr** [comment]
Sorry @charleskawczynski I completely missed your comment. I have no idea how Documenter.jl renders the fonts. Maybe open an issue there?
