### ISSUE TITLE
Alignment anchor is accessing columns outside the print interval

### ISSUE THREAD

**Issue by ronisbr** [ronisbr/PrettyTables.jl#112]
When a table gets cropped, the size of `data_str` is shrunk to fit the screen. In some specific cases, the algorithm is trying to access a data outside the print interval when computing the alignment anchor based on regexes.

# MWE

```julia
julia> using PrettyTables

julia> a = [missing for i = 1:30, j = 1:30];

julia> pretty_table(a, alignment_anchor_regex = Dict(0 => [r"\."]), display_size = (20,30))
```

Ref: https://github.com/JuliaData/DataFrames.jl/pull/2612

**Comment by pdeffebach** [comment]
Wait so this had nothing to do with PooledArrays? I thought that was the source of the bug.

**Comment by ronisbr** [comment]
@pdeffebach no! The source was a very interesting combination of the table size and your terminal size!
