### ISSUE TITLE
latex backend: wrap_table - unexpected behavior

### ISSUE THREAD

**Issue by jo-fleck** [ronisbr/PrettyTables.jl#113]
This is related to the very useful [feature](https://github.com/ronisbr/PrettyTables.jl/pull/85) which allows customizing the environment in which a tex table is wrapped (table, tabular).

Following the info in the merge request and the [documentation](https://ronisbr.github.io/PrettyTables.jl/stable/man/latex_backend/), I expected this command would generate a tex table wrapped in tabular only:

```
open(dir_out * "/tbl_2005.tex", "w") do f
        pretty_table(f, tbl_2005_final, tbl_header, alignment = tbl_alig, wrap_table = false, backend = :latex);
end
```

But I get the error below.

Am I missing something about the correct use of this feature?

Many thanks for your answer and your work on this awesome package!

**MethodError: no method matching _pt_latex(::IOStream, ::PrettyTables.PrintInfo; wrap_table=false)**
Closest candidates are:
  _pt_latex(::IO, ::PrettyTables.PrintInfo; tf, body_hlines, cell_alignment, highlighters, hlines, longtable_footer, noheader, nosubheader, row_number_alignment, table_type, vlines) at /Users/main/.julia/packages/PrettyTables/W16qB/src/backends/latex/print.jl:10 got unsupported keyword argument "wrap_table"
kwerr(::NamedTuple{(:wrap_table,),Tuple{Bool}}, ::Function, ::IOStream, ::PrettyTables.PrintInfo) at error.jl:157
_pt_latex at print.jl:24 [inlined]
_pt(::IOStream, ::Array{Any,2}, ::Array{Any,2}; alignment::Array{Symbol,1}, backend::Symbol, cell_alignment::Nothing, cell_first_line_only::Bool, compact_printing::Bool, filters_row::Nothing, filters_col::Nothing, formatters::Nothing, header_alignment::Symbol, header_cell_alignment::Nothing, renderer::Symbol, row_names::Nothing, row_name_alignment::Symbol, row_name_column_title::String, row_number_column_title::String, show_row_number::Bool, title::String, title_alignment::Symbol, kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:wrap_table,),Tuple{Bool}}}) at private.jl:426
_pt at private.jl:389 [inlined]
#_pretty_table#67 at private.jl:356 [inlined]
_pretty_table at private.jl:338 [inlined]
#pretty_table#51 at print.jl:693 [inlined]
(::PrettyTables.var"#pretty_table##kw")(::NamedTuple{(:alignment, :wrap_table, :backend),Tuple{Array{Symbol,1},Bool,Symbol}}, ::typeof(pretty_table), ::IOStream, ::Array{Any,2}, ::Array{Any,2}) at print.jl:693
(::var"#251#252")(::IOStream) at data_prep.jl:905
open(::var"#251#252", ::String, ::Vararg{String,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at io.jl:325
open(::Function, ::String, ::String) at io.jl:323
top-level scope at data_prep.jl:903

**Comment by ronisbr** [comment]
Hi @jo-fleck !

What version of PrettyTables.jl are you using? The following code works for me:

```julia
julia> a = rand(10,10);

julia> open("teste.txt", "w") do f
           pretty_table(^C

julia> tbl_final = rand(10,10);

julia> tbl_header = rand(10);

julia> open("teste.txt", "w") do f
           pretty_table(f, tbl_final, tbl_header, alignment = :r, wrap_table = false, backend = :latex)
       end
```

This code creates the following file:

```latex
\begin{tabular}{rrrrrrrrrr}
  \hline\hline
  \textbf{0.315815} & \textbf{0.890163} & \textbf{0.744657} & \textbf{0.925774} & \textbf{0.341017} & \textbf{0.0997825} & \textbf{0.520871} & \textbf{0.229045} & \textbf{0.580582} & \textbf{0.361987} \\\hline
  0.314402 & 0.015815 & 0.617236 & 0.217928 & 0.34453 & 0.173734 & 0.244128 & 0.934247 & 0.432371 & 0.309739 \\
  0.706554 & 0.403727 & 0.157959 & 0.630508 & 0.311864 & 0.977308 & 0.301963 & 0.665736 & 0.755667 & 0.947611 \\
  0.437433 & 0.550528 & 0.172049 & 0.69401 & 0.0478971 & 0.0737325 & 0.157498 & 0.449326 & 0.968403 & 0.931359 \\
  0.908271 & 0.593567 & 0.0486632 & 0.251131 & 0.392476 & 0.940374 & 0.978044 & 0.770133 & 0.736416 & 0.0303148 \\
  0.15549 & 0.0951435 & 0.26653 & 0.0613365 & 0.484554 & 0.00403873 & 0.591842 & 0.999599 & 0.424588 & 0.699363 \\
  0.746153 & 0.205745 & 0.819917 & 0.92438 & 0.258325 & 0.0559131 & 0.0763451 & 0.460047 & 0.442912 & 0.234865 \\
  0.399113 & 0.399232 & 0.322378 & 0.515844 & 0.753808 & 0.0820628 & 0.851454 & 0.736999 & 0.913513 & 0.10125 \\
  0.607726 & 0.580109 & 0.550976 & 0.90945 & 0.157469 & 0.563061 & 0.707933 & 0.142139 & 0.751925 & 0.597052 \\
  0.956526 & 0.881061 & 0.0339562 & 0.0187309 & 0.244933 & 0.0390819 & 0.0204754 & 0.685079 & 0.050674 & 0.829834 \\
  0.530961 & 0.494978 & 0.727199 & 0.647603 & 0.653323 & 0.834311 & 0.157956 & 0.637483 & 0.215862 & 0.214033 \\\hline\hline
\end{tabular}
```

**Comment by jo-fleck** [comment]
Hi! Thanks for your reply. 

You're spot on - I updated to v0.11.1 before running the command but just saw in my history that I needed to pre-compile (so I was actually still on v0.10.1. when I tried).

It works now exactly as expected. Sorry for bothering with this (I'll close the comment).

All the best and thanks again for this amazing package!

**Comment by ronisbr** [comment]
> Hi! Thanks for your reply.
> 
> You're spot on - I updated to v0.11.1 before running the command but just saw in my history that I needed to pre-compile (so I was actually still on v0.10.1. when I tried).
> 
> It works now exactly as expected. Sorry for bothering with this (I'll close the comment).

Nice! No problem!



> All the best and thanks again for this amazing package!

Thanks! I am glad it is being useful :)
