### ISSUE TITLE
Profile guided despecialization in PrettyTables.jl

### ISSUE THREAD

**Issue by bkamins** [ronisbr/PrettyTables.jl#116]
@ronisbr - have you tried SnoopCompile.jl to reduce "time to first table" latency? Here is what I get:

```
julia> using DataFrames

julia> df = DataFrame(a=1);

julia> @time PrettyTables.pretty_table(df);
┌───────┐
│     a │
│ Int64 │
├───────┤
│     1 │
└───────┘
  2.624432 seconds (7.73 M allocations: 462.870 MiB, 4.67% gc time, 99.65% compilation time)

julia> @time PrettyTables.pretty_table(df);
┌───────┐
│     a │
│ Int64 │
├───────┤
│     1 │
└───────┘
  0.002711 seconds (312 allocations: 17.281 KiB)
```
and
```
julia> using DataFrames

julia> using SnoopCompile

julia> df = DataFrame(a=1);

julia> x = @snoopi_deep PrettyTables.pretty_table(df)
┌───────┐
│     a │
│ Int64 │
├───────┤
│     1 │
└───────┘
InferenceTimingNode: 1.293810/2.644336 on InferenceFrameInfo for Core.Compiler.Timings.ROOT() with 45 direct children
```
so as you can see 50% of time is spent on inference. Here is the list of most offending functions in PrettyTables.jl:
```
 InferenceTiming: 0.005132/0.056076 on InferenceFrameInfo for PrettyTables._pt_text(::IOContext{Base.TTY}, ::PrettyTables.PrintInfo)
 InferenceTiming: 0.005336/0.053784 on InferenceFrameInfo for PrettyTables._p!(::PrettyTables.Display, ::Crayons.Crayon, ::String, ::Bool, ::Int64)
 InferenceTiming: 0.007063/0.009659 on InferenceFrameInfo for PrettyTables._fill_matrix_data!(::Matrix{String}, ::Matrix{Int64}, ::Matrix{Vector{String}}, ::Matrix{Vector{Int64}}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Int64, ::Vector{Int64}, ::PrettyTables.ColumnTable, ::Vector{Any}, ()::Tuple{}, ::PrettyTables.Display, ::Bool, ::Bool, ::Bool, ::Bool, ::Vector{Bool}, ::Bool, ::Bool, ::Vector{Int64}, ::Bool, Val{:print}()::Val{:print}, ::Symbol)
 InferenceTiming: 0.007161/0.039494 on InferenceFrameInfo for PrettyTables._fill_row_name_column!(::Matrix{String}, ::Matrix{Int64}, ::Matrix{Vector{String}}, ::Matrix{Vector{Int64}}, ::Vector{Int64}, ::AbstractVector{T} where T, ::Vector{Int64}, ::Vector{Int64}, ::Int64, ::Bool, Val{:show}()::Val{:show}, ::String)
 InferenceTiming: 0.009759/0.010229 on InferenceFrameInfo for PrettyTables._fill_matrix_data!(::Matrix{String}, ::Matrix{Int64}, ::Matrix{Vector{String}}, ::Matrix{Vector{Int64}}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Int64, ::Vector{Int64}, ::Any, ::Any, ::Tuple, ::PrettyTables.Display, ::Bool, ::Bool, ::Bool, ::Bool, ::Vector{Bool}, ::Bool, ::Bool, ::Vector{Int64}, ::Bool, Val{:print}()::Val{:print}, ::Symbol)
 InferenceTiming: 0.010065/0.139447 on InferenceFrameInfo for PrettyTables._preprocess_Tables_column(::DataFrame, ::Vector{String})
 InferenceTiming: 0.010801/0.029830 on InferenceFrameInfo for PrettyTables._apply_alignment_anchor_regex!(::Matrix{Vector{String}}, ::Matrix{Vector{Int64}}, ::Vector{Int64}, ::Vector{Symbol}, ::Vector{Int64}, ::Vector{Int64}, ::Int64, ::Symbol, ::Dict{Int64, Symbol}, ::Dict{Int64, Vector{Regex}}, ::Dict{Tuple{Int64, Int64}, Symbol}, ::Vector{Bool}, ::Vector{Int64})
 InferenceTiming: 0.012108/0.029341 on InferenceFrameInfo for PrettyTables._create_printing_recipe(::PrettyTables.Display, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Int64, ::Int64, ::Symbol, ::Bool, ::Bool, ::Symbol)
 InferenceTiming: 0.023596/0.038380 on InferenceFrameInfo for PrettyTables.var"#_pt_text#98"(::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Symbol, ::Dict{Int64, Symbol}, ::Dict{Int64, Vector{Regex}}, ::Bool, ::Vector{Int64}, nothing::Nothing, ::Symbol, ::Symbol, ::Bool, ::Int64, ::Int64, ::Tuple{Int64, Int64}, ::Bool, ::Int64, ()::Tuple{}, nothing::Nothing, ::Bool, ::Int64, ::Int64, ::Bool, ::Bool, ::Bool, ::Bool, ::Crayons.Crayon, ::Crayons.Crayon, ::Symbol, ::Bool, ::Bool, ::PrettyTables.TextFormat, ::Bool, ::Crayons.Crayon, ::Bool, ::Symbol, nothing::Nothing, _pt_text::typeof(PrettyTables._pt_text), ::IOContext{Base.TTY}, ::PrettyTables.PrintInfo)
 InferenceTiming: 0.034976/0.039088 on InferenceFrameInfo for PrettyTables._fill_matrix_data!(::Matrix{String}, ::Matrix{Int64}, ::Matrix{Vector{String}}, ::Matrix{Vector{Int64}}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64}, ::Int64, ::Vector{Int64}, ::Any, ::Any, ::Tuple, ::PrettyTables.Display, ::Bool, ::Bool, ::Bool, ::Bool, ::Vector{Bool}, ::Bool, ::Bool, ::Vector{Int64}, ::Bool, Val{:show}()::Val{:show}, ::Symbol)
 InferenceTiming: 0.114441/0.762466 on InferenceFrameInfo for PrettyTables.var"#_pt_text#98"(::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Symbol, ::Dict{Int64, Symbol}, ::Dict{Int64, Vector{Regex}}, ::Bool, ::Vector{Int64}, nothing::Nothing, ::Symbol, ::Symbol, ::Bool, ::Int64, ::Int64, ::Tuple{Int64, Int64}, ::Bool, ::Int64, ()::Tuple{}, nothing::Nothing, ::Bool, ::Int64, ::Int64, ::Bool, ::Bool, ::Bool, ::Bool, ::Crayons.Crayon, ::Crayons.Crayon, ::Symbol, ::Bool, ::Bool, ::PrettyTables.TextFormat, ::Bool, ::Crayons.Crayon, ::Bool, ::Symbol, nothing::Nothing, _pt_text::typeof(PrettyTables._pt_text), ::IO, ::PrettyTables.PrintInfo)
```

In general my experience from DataFrames.jl is that all methods that do not do a lot of work and at the same time may get input of wide array of types should be despecialized. See https://github.com/JuliaData/DataFrames.jl/pull/2691.

**Comment by bkamins** [comment]
Ah - you might also consider adding precompile statements to the package (maybe you already have done this?)

**Comment by ronisbr** [comment]
> Ah - you might also consider adding precompile statements to the package (maybe you already have done this?)

I tried this, adding all the precompilation from SnoopCompile and I was not able to improve things substantially in PrettyTables.jl. I think I could reduce it only by 10%.

> In general my experience from DataFrames.jl is that all methods that do not do a lot of work and at the same time may get input of wide array of types should be despecialized. See [JuliaData/DataFrames.jl#2691](https://github.com/JuliaData/DataFrames.jl/pull/2691).

This is something I did not try. Thanks for the suggestion!

**Comment by bkamins** [comment]
The general conclusion I have is: since you pay 0.002 seconds to plot after compilation and 2.6 seconds to do the first plot then if by despecializing you increase 0.002 seconds ten times to even e.g. 0.02 seconds no one will notice, but if this will reduce 2.6 seconds to eg. 1.6 seconds it is going to be noticeable.

**Comment by ronisbr** [comment]
Hi @bkamins 

Can you please try with `master` and tell me if it was improved for you? I did a **lot** of modifications related to type instabilities (that were affecting inference) and also a bit of despecialization.

Before, I had here:

```julia
julia> using DataFrames

julia> df = DataFrame(a = 1);

julia> @time PrettyTables.pretty_table(df)
┌───────┐
│     a │
│ Int64 │
├───────┤
│     1 │
└───────┘
  2.285746 seconds (7.54 M allocations: 446.763 MiB, 5.32% gc time, 99.91% compilation time)
```

```julia
julia> using DataFrames

julia> df = DataFrame(a = 1);

julia> @time PrettyTables.pretty_table(df)
┌───────┐
│     a │
│ Int64 │
├───────┤
│     1 │
└───────┘
  1.752344 seconds (6.00 M allocations: 351.662 MiB, 5.79% gc time, 99.93% compilation time)
```

In the process, we have a breaking change that does not affect DataFrames. It is related about how the backend is selected. Before, we used a symbol `backend = :html`. Now we use a `Val(:html)`. This reduced the time to print the first table in LaTeX and HTML 4x (from 2s to 0.5s) since the compiler now know that it should precompile those methods.

**Comment by bkamins** [comment]
Yes, things are better by about 0.5 second; still inference is relevant though (maybe this cannot be helped):
```
julia> using DataFrames

julia> using SnoopCompile

julia> df = DataFrame(a=1);

julia> x = @snoopi_deep PrettyTables.pretty_table(df)
┌───────┐
│     a │
│ Int64 │
├───────┤
│     1 │
└───────┘
InferenceTimingNode: 1.093143/2.091411 on InferenceFrameInfo for Core.Compiler.Timings.ROOT() with 29 direct children
```

There is one function that generates majority of inference cost:
```
InferenceTiming: 0.094593/0.615940 on InferenceFrameInfo for PrettyTables.var"#_pt_text#94"(::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Crayons.Crayon, ::Symbol, ::Dict{Int64, Symbol}, ::Dict{Int64, Vector{Regex}}, ::Bool, ::Vector{Int64}, nothing::Nothing, ::Symbol, ::Symbol, ::Bool, ::Int64, ::Int64, ::Tuple{Int64, Int64}, ::Bool, ::Int64, ()::Tuple{}, nothing::Nothing, ::Bool, ::Int64, ::Int64, ::Bool, ::Bool, ::Bool, ::Bool, ::Crayons.Crayon, ::Crayons.Crayon, ::Symbol, ::Bool, ::Bool, ::PrettyTables.TextFormat, ::Bool, ::Crayons.Crayon, ::Bool, ::Symbol, nothing::Nothing, _pt_text::typeof(PrettyTables._pt_text), ::Base.RefValue{Any}, ::PrettyTables.PrintInfo)
```
It seems to be some anonymous function and maybe it is impossible to improve this (I have quickly checked and in this function there are many other functions called none of which hugely impacts the timing - rather we have a lot of small slowdowns).

I have also noticed that a lot of time is spent in `getproperty`. Maybe it is unavoidable, but a typical trick (if these are some your internal structures), to replace e.g. `NamedTuple` by `Dict`. Not sure if this would help.

**Comment by ronisbr** [comment]
Hi @bkamins 

The idea about `getproperty` was very good. But it turns out that everything is coming from the keyword arguments and not `NamedTuple`s I am using in the code. I think we are very close to the limit in optimization using despecialization. I will try, now that the code is much stable, to add some precompilation statements.

**Comment by ronisbr** [comment]
Hi @bkamins,

We need to make a decision now. I tried precompilation and I got interesting results:

**Without precompilation**

```julia
julia> @time using PrettyTables
[ Info: Precompiling PrettyTables [08abe8d2-0d0c-5749-adfa-8a2ac140af0d]
  1.977869 seconds (1.53 M allocations: 90.528 MiB, 0.66% gc time, 28.18% compilation time)

julia> @time using PrettyTables
  0.036923 seconds (49.94 k allocations: 4.437 MiB, 8.20% compilation time)

julia> a = [1 2 3; 4 5 6; 7 8 9];

julia> @time pretty_table(a)
┌────────┬────────┬────────┐
│ Col. 1 │ Col. 2 │ Col. 3 │
├────────┼────────┼────────┤
│      1 │      2 │      3 │
│      4 │      5 │      6 │
│      7 │      8 │      9 │
└────────┴────────┴────────┘
  1.388481 seconds (4.18 M allocations: 242.733 MiB, 4.85% gc time, 99.93% compilation time)
```

**With precompilation**

```julia
julia> @time using PrettyTables
[ Info: Precompiling PrettyTables [08abe8d2-0d0c-5749-adfa-8a2ac140af0d]
 12.363404 seconds (1.98 M allocations: 126.067 MiB, 0.22% gc time, 4.37% compilation time)

julia> @time using PrettyTables
  0.328231 seconds (503.60 k allocations: 40.080 MiB, 2.99% gc time, 0.94% compilation time)

julia> @time pretty_table(a)
┌────────┬────────┬────────┐
│ Col. 1 │ Col. 2 │ Col. 3 │
├────────┼────────┼────────┤
│      1 │      2 │      3 │
│      4 │      5 │      6 │
│      7 │      8 │      9 │
└────────┴────────┴────────┘
  0.814206 seconds (1.28 M allocations: 75.638 MiB, 3.13% gc time, 99.89% compilation time)
```

I am not sure what is the best tradeoff here.

**Comment by ronisbr** [comment]
There is a middle approach, in which I considered only the a file inside the test set related to the Text backend (which is the slowest to print the first table):

```julia
julia> @time using PrettyTables
[ Info: Precompiling PrettyTables [08abe8d2-0d0c-5749-adfa-8a2ac140af0d]
  3.061061 seconds (1.67 M allocations: 101.156 MiB, 0.34% gc time, 18.15% compilation time)

julia> @time using PrettyTables
  0.110016 seconds (191.44 k allocations: 15.156 MiB, 2.84% compilation time)

julia> a = [1 2 3; 4 5 6; 7 8 9];

julia> @time pretty_table(a)
┌────────┬────────┬────────┐
│ Col. 1 │ Col. 2 │ Col. 3 │
├────────┼────────┼────────┤
│      1 │      2 │      3 │
│      4 │      5 │      6 │
│      7 │      8 │      9 │
└────────┴────────┴────────┘
  0.827168 seconds (1.34 M allocations: 79.568 MiB, 1.95% gc time, 99.88% compilation time)
```

For DataFrames, using no precompilation:

```julia
julia> @time using DataFrames
  0.707026 seconds (898.16 k allocations: 66.330 MiB, 0.47% compilation time)

julia> @time using DataFrames
  0.707026 seconds (898.16 k allocations: 66.330 MiB, 0.47% compilation time)

julia> df = DataFrame(a = 1);

julia> @time show(df)
1×1 DataFrame
 Row │ a
     │ Int64
─────┼───────
   1 │     1  2.418383 seconds (7.67 M allocations: 448.910 MiB, 6.43% gc time, 99.95% compilation time)
```

using this last version:

```Julia
julia> @time using DataFrames
  0.793988 seconds (1.06 M allocations: 77.752 MiB, 2.22% gc time, 0.48% compilation time)

julia> df = DataFrame(a = 1);

julia> @time show(df)
1×1 DataFrame
 Row │ a
     │ Int64
─────┼───────
   1 │     1  2.041192 seconds (5.96 M allocations: 353.184 MiB, 4.39% gc time, 99.94% compilation time)
```

and using the full precompilation:

```julia
julia> @time using DataFrames
  1.063715 seconds (1.28 M allocations: 96.933 MiB, 2.79% gc time, 0.29% compilation time)

julia> df = DataFrame(a = 1);

julia> @time show(df)
1×1 DataFrame
 Row │ a
     │ Int64
─────┼───────
   1 │     1  2.162700 seconds (5.70 M allocations: 337.093 MiB, 9.39% gc time, 99.95% compilation time)
```

Hence, for DataFrames, the middle approach is far better. Question: are those increases in loading time acceptable?

**Comment by bkamins** [comment]
In DataFrames.jl we use kind of your middle approach also. I understand that the loading time would increase by 0.1 second for middle approach. Right? Then it is acceptable as you pay 0.1 second on load to save 0.4 second on first plot (and since 99% of times one will do the plot this is clearly saving time).

This was the rule we used in DataFrames.jl to determine precompilation threshold i.e. that load time + common operations time should decrease. You have an easier task as essentially you have only one task (printing), while in DataFrames.jl we have many different tasks.

What you could consider is not to precompile methods related to HTML or LaTeX output as they are not used by DataFrames.jl yet (this maybe will reduce load time without impacting time to first table in REPL time). We could add these precompilations later when we add HTML and LaTeX support in DataFrames.jl. What do you think?

**Comment by ronisbr** [comment]
> In DataFrames.jl we use kind of your middle approach also. I understand that the loading time would increase by 0.1 second for middle approach. Right? Then it is acceptable as you pay 0.1 second on load to save 0.4 second on first plot (and since 99% of times one will do the plot this is clearly saving time).

Yes! That's what happened.

> This was the rule we used in DataFrames.jl to determine precompilation threshold i.e. that load time + common operations time should decrease. You have an easier task as essentially you have only one task (printing), while in DataFrames.jl we have many different tasks.

Good point! I will tweak more and I promise I will take into account DataFrames TPFT to optimize this.

> What you could consider is not to precompile methods related to HTML or LaTeX output as they are not used by DataFrames.jl yet (this maybe will reduce load time without impacting time to first table in REPL time). We could add these precompilations later when we add HTML and LaTeX support in DataFrames.jl. What do you think?

That's precisely what I called "middle approach". However, I think I can tune this better. Let's see.

**Comment by bkamins** [comment]
Thank you for working on this!

**Comment by ronisbr** [comment]
Thank you for the amazing tips :)

**Comment by ronisbr** [comment]
@bkamins I pushed the precompilation to `master`. I think we can close this :) If you can test, I will appreciate!

**Comment by bkamins** [comment]
Great. I go down from 1.92 sec to 1.53 sec with first table output on my machine.
DataFrames.jl load time went up from 0.905 sec to 1.010 sec, so it is all as expected and reasonable. Thank you!

**Comment by ronisbr** [comment]
@bkamins btw, I am modifying the API. The old one will work but it will be marked as deprecated. The header will not be an argument anymore, but a keyword. It will also be a Vector of Vectors instead of a Matrix, which was a suggestion you gave me sometime ago. This improved the inference in some cases. As soon as I get this finished, I submit a PR to update the DataFrames code.

With this API modification and the precompilation, I think I can tag the v1.0 :)

**Comment by ronisbr** [comment]
The new API seems promising in terms of speed of tables that complies with Table.jl (DataFrames.jl is printed using the same code):

**Old**

```julia
julia> @time using PrettyTables
  0.109649 seconds (184.68 k allocations: 14.694 MiB, 2.76% compilation time)

julia> a = (a = 1:10, b = 2:2:20, c = 3.0:3.0:30.0);

julia> @time pretty_table(a)
┌───────┬───────┬─────────┐
│     a │     b │       c │
│ Int64 │ Int64 │ Float64 │
├───────┼───────┼─────────┤
│     1 │     2 │     3.0 │
│     2 │     4 │     6.0 │
│     3 │     6 │     9.0 │
│     4 │     8 │    12.0 │
│     5 │    10 │    15.0 │
│     6 │    12 │    18.0 │
│     7 │    14 │    21.0 │
│     8 │    16 │    24.0 │
│     9 │    18 │    27.0 │
│    10 │    20 │    30.0 │
└───────┴───────┴─────────┘
  1.254110 seconds (3.42 M allocations: 200.028 MiB, 2.73% gc time, 99.88% compilation time)
```

**New**

```julia
julia> @time using PrettyTables
  0.112544 seconds (196.82 k allocations: 15.499 MiB, 3.56% compilation time)

julia> a = (a = 1:10, b = 2:2:20, c = 3.0:3.0:30.0);

julia> @time pretty_table(a)
┌───────┬───────┬─────────┐
│     a │     b │       c │
│ Int64 │ Int64 │ Float64 │
├───────┼───────┼─────────┤
│     1 │     2 │     3.0 │
│     2 │     4 │     6.0 │
│     3 │     6 │     9.0 │
│     4 │     8 │    12.0 │
│     5 │    10 │    15.0 │
│     6 │    12 │    18.0 │
│     7 │    14 │    21.0 │
│     8 │    16 │    24.0 │
│     9 │    18 │    27.0 │
│    10 │    20 │    30.0 │
└───────┴───────┴─────────┘
  1.057492 seconds (2.47 M allocations: 146.558 MiB, 2.43% gc time, 99.86% compilation time)
```

A 0.2s improvement in printing with a 0.003s loss in loading.

**Comment by bkamins** [comment]
This is great. I assume that for DataFrames.jl these changes will be transparent right (i.e. you will change the internal code only)?

When do you plan to release 1.0 of PrettyTables.jl?

**Comment by ronisbr** [comment]
> This is great. I assume that for DataFrames.jl these changes will be transparent right (i.e. you will change the internal code only)?

Yes, it will work with and without modification (the old API is deprecated but working). However, as soon as I tag v0.12, I will submit a PR to change the internal code. There will be no visible change.

> When do you plan to release 1.0 of PrettyTables.jl?

My plan is to tag v0.12 today, wait one or two weeks for some bug reports, and then tag 1.0. Hence, the milestone will be to stabilize HTML and LaTeX by v1.1 and then port the code inside DataFrames to use PrettyTables for those two backends.

Are you OK with that?

**Comment by bkamins** [comment]
Yes. I will then wait with DataFrames.jl 1.0 release for PrettyTabels.jl 1.0 release and add 1.0 PrettyTables.jl requirement. So this means that we release DataFrames.jl 1.0 by end of April, which is OK.

CC @nalimilan
