### ISSUE TITLE
Support AbstractDict and not just OrderedDict

### ISSUE THREAD

**Issue by pdeffebach** [ronisbr/PrettyTables.jl#120]
Currently `pretty_table(d::Dict)` works but not `pretty_table(d::OrderedDict)`. 

I think it would all "just work" by changing this line: 

https://github.com/ronisbr/PrettyTables.jl/blob/f122616a54556b6f698ee26b6448e45a1cc5d579/src/private.jl#L325

**Comment by ronisbr** [comment]
Hi @pdeffebach 

Thanks for the tip! I think it should be working now. Can you please test using `master`?

**Comment by pdeffebach** [comment]
Works perfectly! Thanks a ton.
