### ISSUE TITLE
Julia 1.5 support

### ISSUE THREAD

**Issue by ablaom** [ronisbr/PrettyTables.jl#121]
According to the release notes for version 0.12.0, support for Julia 1.5 has been dropped. However, the current project file still has [compat] julia = "1.0". 

What am I missing here?

**Comment by ronisbr** [comment]
Hi @ablaom !

Sorry for the confusion. The commit means that we are not testing PrettyTables.jl against Julia 1.5 specifically. The tests occurs only in versions 1.0 and 1.6 for now.
