### ISSUE TITLE
Escape characters in LaTeX

### ISSUE THREAD

**Issue by Entze** [ronisbr/PrettyTables.jl#125]
Currently strings seem not to be escaped.

For example:

```julia
using PrettyTables

header = ["percent", "dollar", "curly braces", "lt"]
pretty_table(data; header=header, backend = Val(:latex))
```
produces:
```latex
\begin{table}
  \begin{tabular}{rrrr}
    \hline\hline
    \textbf{percent} & \textbf{dollar} & \textbf{curly braces} & \textbf{lt} \\\hline
    100% & 50$ & {} & < \\\hline\hline
  \end{tabular}
\end{table}

```

This produces a non-valid LaTeX table as the percent is the symbol for a line comment.

**Comment by ronisbr** [comment]
Nice catch! Thanks for the report. Yes, we need to take more care while escaping characters in LaTeX.

**Comment by ronisbr** [comment]
@Entze 

Do your agree with the following escaping:

```julia
\begin{table}
  \begin{tabular}{rrrr}
    \hline\hline
    \textbf{percent} & \textbf{dollar} & \textbf{curly braces} & \textbf{lt} \\\hline
    100\% & 50\$ & \{\} & $<$ \\\hline\hline
  \end{tabular}
\end{table}
```

I am not sure about the `<`.

**Comment by ronisbr** [comment]
Unfortunately, I cannot escape `$`. Otherwise, we cannot add a LaTeX command in the table inside the printed data.

**Comment by Entze** [comment]
> @Entze
> 
> Do your agree with the following escaping:

Yes i think that is sufficient! It at least allows for generation of valid LaTeX. Otherwise the user needs to escape themselves.

> I am not sure about the `<`.

That was an example for escaping in HTML (for future escaping needs).

**Comment by ronisbr** [comment]
> Yes i think that is sufficient! It at least allows for generation of valid LaTeX. Otherwise the user needs to escape themselves.

Nice! I committed this to `master` . Can you please test?

> hat was an example for escaping in HTML (for future escaping needs).

Ah OK! Yes, I indeed need to polish the HTML and LaTeX backends now. Thanks for this bug report :)

**Comment by Entze** [comment]
I tested with Julia v1.4:


```julia
using PrettyTables

header = ["percent", "dollar", "curly braces", "lt"]
data = ["%" "\$" "{}" "<"]
pretty_table(data; header=header, backend = Val(:latex))
```

produces

```latex
\begin{table}
  \begin{tabular}{rrrr}
    \hline\hline
    \textbf{percent} & \textbf{dollar} & \textbf{curly braces} & \textbf{lt} \\\hline
    \% & $ & {} & < \\\hline\hline
  \end{tabular}
\end{table}
```
as (at least for the percent sign) intended.
