### ISSUE TITLE
Recent change to Tables.istable

### ISSUE THREAD

**Issue by quinnj** [ronisbr/PrettyTables.jl#13]
Just wanted to leave a quick note about the most recent release of Tables 0.2, which made `Tables.istable` more conservative in terms of what it considers Tables.jl-compatible. The truth is that there are some objects that are valid tables, but can't be determined as such until you start iterating them (like Generators of NamedTuples, or Vector{Any} where elements are NamedTuples).

One thing you could change would be to remove [this line](https://github.com/ronisbr/PrettyTables.jl/blob/a5030140c2ceec5cef9af57f24d5ab5c3be31476/src/print.jl#L311). Just calling `Tables.columns(table)` will attempt to create a table from the input, and throw its own error if the input isn't a valid table. The advantage is that `Tables.columns` will treat these "nonstandard" objects as valid tables (Generators, Vector{Any}, etc.). If you'd still like to throw your own error, you can just wrap your `Tables.columns` call in a try-catch.

Anyway, hope this is helpful.

**Comment by ronisbr** [comment]
Done! Thanks @quinnj 

It seems to be working very nice.
