### ISSUE TITLE
[Feature] Support DimensionalData.jl

### ISSUE THREAD

**Issue by rapus95** [ronisbr/PrettyTables.jl#132]
having support for that generalization of NamedDims.jl and AxisArrays.jl would be awesome!

**Comment by ronisbr** [comment]
Hi @rapus95 !

What kind of support you are thinking of?

**Comment by rapus95** [comment]
rendering the dimension names next to the axes would be awesome!

**Comment by ronisbr** [comment]
Hum, I think you can do this using the current API. I really cannot support this feature inside PrettyTables.jl because it would required adding those two packages as dependencies. We should avoid this to keep the loading time small. Sorry!
