### ISSUE TITLE
custom style attributes in HTMLDecoration

### ISSUE THREAD

**Issue by disberd** [ronisbr/PrettyTables.jl#134]
I would first like to thank you for this package as it is very neat!

I was playing around with the HTML backend to show nice tables in Pluto and noticed that the HTMLHighlighter currently only accept five possible style attributes.

Since the style of highlighters are directly inline on the elements, I believe it would be very powerful if one could provide an additional argument to decoration containing an arbitrary set of style attributes. 
This would allow the ultimate level of cell customization and could be simply left empty at default for normal behavior.

I believe the argument itself could already expect a dict of various style attributes so that it could be directly merged with the style dict at the end of:

https://github.com/ronisbr/PrettyTables.jl/blob/41d6bf5ba806a99cc5bc0aadda1cd3d2776e6657/src/backends/html/types.jl#L27-L37

Similarly to what is already done in the overall cell style dict in:

https://github.com/ronisbr/PrettyTables.jl/blob/41d6bf5ba806a99cc5bc0aadda1cd3d2776e6657/src/backends/html/print.jl#L328-L333

Is this something that you would consider feasible or would it break some design guidelines/patterns in this package?

I would be happy to help with PR testing in case this modification could fit the package.

Edit: Added also reference to the current code to create a Dict

**Comment by ronisbr** [comment]
Hi @disberd !

Thanks for the request!

> Is this something that you would consider feasible or would it break some design guidelines/patterns in this package?

Yes, sure! The HTML backend is not stable yet and we can break everything if we want 😅

I agree with you. It will be better if we let the user free to select the style instead of limiting to a set of decorations. I will see how can I do this.

**Comment by disberd** [comment]
I just edited my original post while you were replying to provide some more details :D.

My initial very simple idea would be to simply add a keyword argument `style` to the HTMLDecoration, force it to be a Dict{String,String}, and use it to directly initialize the `style` Dict inside the `Dict(::HTMLDecoration)` function.

This way existing custom property specifically defined by keyword arguments would override the values in the dict if present.

If you are fine with testing this I could just submit a PR

**Comment by ronisbr** [comment]
> My initial very simple idea would be to simply add a keyword argument style to the HTMLDecoration, force it to be a Dict{String,String}, and use it to directly initialize the style Dict inside the Dict(::HTMLDecoration) function.
>
> This way existing custom property specifically defined by keyword arguments would override the values in the dict if present.

Seems good to me! We have those keywords for "common" decorations and a "general" `style` for more complex one.

> If you are fine with testing this I could just submit a PR

Sure! Thank you very much!
