### ISSUE TITLE
Add option to prettily print a wide table with only a few rows

### ISSUE THREAD

**Issue by ablaom** [ronisbr/PrettyTables.jl#138]
Sometimes one wants to print a table which has a lot of columns but not too many rows, which can be done prettily if the header is printed vertically instead of horizontally, with rows and columns interchanged, as here:

name         || Bob | Jane   | Ng     ||
age            || 12    | 22       | 4       ||
father        || Ben | Roger | Mary ||
.                  .            .          .
.                  .            .          .
.                  .            .          .
.                  .            .          .
ndevices  || 2     |     5          |   1 ||

Be great to have this.

**Comment by ronisbr** [comment]
Hi @ablaom !

This is indeed a very nice feature to have. Can you please check if this is the same feature requested here: https://github.com/ronisbr/PrettyTables.jl/issues/87 ? Thanks!

**Comment by ablaom** [comment]
Yep!
