### ISSUE TITLE
Slow compact printing of large table

### ISSUE THREAD

**Issue by aminnj** [ronisbr/PrettyTables.jl#140]
I have a large (60M+ row) *lazy* table `t` that feels a bit unresponsive when (compactly) printing out on the terminal:
```julia
julia> t
 Row │  nMuon    Muon_charge          Muon_mass               ⋯
     │  UInt32   Vector{Int32}        Vector{Float32}         ⋯
─────┼─────────────────────────────────────────────────────────
 1   │  2        [-1, -1]             [0.106, 0.106]          ⋯
 2   │  2        [1, -1]              [0.106, 0.106]          ⋯
 3   │  1        [1]                  [0.106]                 ⋯
 4   │  4        [1, 1, 1, 1]         [0.106, 0.106, 0.106, 0 ⋯
 5   │  4        [-1, -1, 1, 1]       [0.106, 0.106, 0.106, 0 ⋯
 6   │  3        [-1, 1, -1]          [0.106, 0.106, 0.106]   ⋯
 7   │  2        [-1, 1]              [0.106, 0.106]          ⋯
 8   │  2        [1, -1]              [0.106, 0.106]          ⋯
 9   │  2        [-1, 1]              [0.106, 0.106]          ⋯
 10  │  2        [-1, 1]              [0.106, 0.106]          ⋯
  ⋮  │    ⋮               ⋮                          ⋮        ⋱
                             1 column and 61540403 rows omitted
```
```julia
julia> @time repr(t; context=:limit=>true)
  0.594255 seconds
# vs
julia> @time repr(t[1:10]; context=:limit=>true)
  0.005187 seconds
```
The profiler points to 
https://github.com/ronisbr/PrettyTables.jl/blob/e52626b68f478563af94615da766371f9c2459b0/src/private.jl#L231
and
https://github.com/ronisbr/PrettyTables.jl/blob/e52626b68f478563af94615da766371f9c2459b0/src/private.jl#L261

Is there a way to skip the generation of this large vector of ones when compactly printing?

**Comment by aminnj** [comment]
I was playing around with making the array of row indices lazy (`UnitRange`) if there's no row filter specified: https://github.com/aminnj/PrettyTables.jl/commit/123e756f60468841530e3bf11f155b6921a41961
I see about a 4x speedup. If you think this is a good approach, I'll double check the remaining places to use `AbstractVector` and make a PR.

**Comment by ronisbr** [comment]
Hi @aminnj !

Thanks! This proposal seems very good :) My only concern is by changing the function signature from `Vector` to `AbstractVector`, we might have to add some pre-compilation statements to avoid degradation of the time to print the first table. Can you please to a test for me?

1. Initialize Julia and create a matrix (not random) `m`.
2. Execute:
    ```julia
    @time using PrettyTables
    @time pretty_table(m)
   ```

This procedure should be done with and without your patch to see if we have any problems.

Thanks!

**Comment by aminnj** [comment]
@ronisbr, here's what I get. The times vary within ~5-10% over a few tries, but they are still similar between the two.

### master
```julia
julia> m = [collect(0:1:100) collect(0:2:200) collect(0:3:300)];

julia> @time using PrettyTables
  0.263265 seconds (353.57 k allocations: 22.426 MiB)

julia> @time pretty_table(m);
  1.206283 seconds (1.56 M allocations: 83.666 MiB, 8.82% gc time, 99.90% compilation time)
```

### after

```julia
julia> m = [collect(0:1:100) collect(0:2:200) collect(0:3:300)];

julia> @time using PrettyTables
  0.263684 seconds (365.00 k allocations: 23.014 MiB)

julia> @time pretty_table(m);
  1.327629 seconds (2.61 M allocations: 139.204 MiB, 11.73% gc time, 27.08% compilation time)
```

**Comment by ronisbr** [comment]
I think we can have something a little bit more different. We can move the filter computation to an external function and call it in each backend. In this case, we can have a keyword to set the maximum number of lines to be processed. Thus, in case of compact printing, we will save a lot of things.

**Comment by aminnj** [comment]
@ronisbr is this something you're planning on implementing? I can't say I'm familiar enough with the internals to know exactly what you propose. Personally, I'm using `Union{Vector{Int},UnitRange{Int}}` locally as that was an easy enough change that works.

**Comment by ronisbr** [comment]
Yes! I am planning to do this. I will try to fix this in this weekend :)

**Comment by ronisbr** [comment]
Hi @aminnj 

Just a heads up, I tried to implement my strategy and the time to print the first table went from 0,84s to 1,4s :( I will need more work to solve this issue.

**Comment by Moelf** [comment]
sprinkle some `@nospecialize`?

**Comment by ronisbr** [comment]
I tried `@nospecialize` together with pre-compilation but I could not solve the problem yet.

**Comment by aminnj** [comment]
I just now tried updating the precompile statements with the `AbstractVector` fix from earlier in this thread.

```julia
m = [collect(0:1:100) collect(0:2:200) collect(0:3:300)];
@time using PrettyTables
@time pretty_table(m);
```

### `master`
```
  0.257096 seconds (360.51 k allocations: 22.883 MiB)
  1.158159 seconds (1.56 M allocations: 83.592 MiB, 8.28% gc time, 99.90% compilation time)
```
### lazy (`AbstractVector`, precompiled)
```
  0.278997 seconds (375.09 k allocations: 23.677 MiB)
  1.165593 seconds (1.51 M allocations: 80.982 MiB, 8.60% gc time, 99.89% compilation time)
```
and that appears to reduce the time back to `master`. Would a PR be welcomed?

**Comment by ronisbr** [comment]
This is very nice! I think this can solve the bug! I will still need in the future to fix the design of the filters, but it will take sometime.
