### ISSUE TITLE
Textual representation of `missing`

### ISSUE THREAD

**Issue by jabortell** [ronisbr/PrettyTables.jl#145]
I have a DataFrame with many columns and many missing values, and I was looking to reduce the textual busyness by changing the textual representation of `Missing` from `"missing"` to `"?"` or `""`. I first thought to override `Base.show` / `Base.print`, but when that didn't work, I poked around the code, and it seems that via this line in `src/backends/text/cell_parse.jl`, it is hardcoded?

```julia
@inline _parse_cell_text(cell::Missing; kwargs...) = ["missing"]
```

Just want to confirm whether I should be able to override `"missing"`, and if so, what is the recommended way to do it for DataFrames / PrettyTable. If not, I'd be thrilled to see a parameter for it.

**Comment by ronisbr** [comment]
Hi @jabortell !

What you need is a formatter, that formats a cell before it is converted to a string:

```julia
julia> using DataFrames

julia> df = DataFrame(x = [n % 2 == 0 ? missing : 10^6/factorial(n) for n in 2:10]);

julia> formatter(v, i, j) = v isa Missing ? "?" : v
formatter (generic function with 1 method)

julia> show(df, formatters = formatter)
9×1 DataFrame
 Row │ x
     │ Float64?
─────┼──────────────
   1 │    ?
   2 │    1.66667e5
   3 │    ?
   4 │ 8333.33
   5 │    ?
   6 │  198.413
   7 │    ?
   8 │    2.75573
   9 │    ?
```

**Comment by jabortell** [comment]
Oh dang that's exactly it! Thank you @ronisbr!

**Comment by ronisbr** [comment]
Nice! :)
