### ISSUE TITLE
Suppressing the line under the header

### ISSUE THREAD

**Issue by lbilli** [ronisbr/PrettyTables.jl#15]
I like this package and its level of customizations.

A feature I miss is the possibility to remove the line between header and data the same way the top and bottom lines can be removed.

Thanks.

**Comment by ronisbr** [comment]
Hi @lbilli 

I will implement something related to this. Indeed, there is no workaround for this in the moment.

**Comment by ronisbr** [comment]
Sorry @lbilli for the the long delay!

I have implemented the option `header_line` in the format so that you can do what you want :)
