### ISSUE TITLE
How to print blank (for `missing` or `nothing`)

### ISSUE THREAD

**Issue by KronosTheLate** [ronisbr/PrettyTables.jl#150]
Could a section to the documentation be added for how to print empty table-cells? I just went looking for it, and ended up guessing how to do it (By printing an empty string)

This is especially relevant for when there are values `missing` or `nothing`.

Possibly the best way to do this is to add a filter option, something like `omit_missing` or `omit_nothing`, which would replace `missing` or `nothing` with the empty string `""`

I am making an issue as opposed to a PR because I am not sure what the best implementation of my suggestion is, or if there is another way that I don't know of.

**Comment by ronisbr** [comment]
Hi @KronosTheLate !

I really do not want to replace the default behavior of the renderers (`print` or `show`). However, you can easily do this by using formatters:

```julia
julia> using PrettyTables

julia> ft = (v, i, j) -> (ismissing(v) || isnothing(v)) ? "" : v
#3 (generic function with 1 method)

julia> data = [1 2 nothing missing; 1 nothing 3 4; 1 nothing nothing missing];

julia> pretty_table(data, formatters = ft)
┌────────┬────────┬────────┬────────┐
│ Col. 1 │ Col. 2 │ Col. 3 │ Col. 4 │
├────────┼────────┼────────┼────────┤
│      1 │      2 │        │        │
│      1 │        │      3 │      4 │
│      1 │        │        │        │
└────────┴────────┴────────┴────────┘
```

**Comment by KronosTheLate** [comment]
Looks perfect!
Is there any reason not to add this as a predefined formatter? Under https://ronisbr.github.io/PrettyTables.jl/stable/man/formatters/#Predefined-formatters.
Alternativly, it can be added as an example, killing two birds with one stone, right?

**Comment by ronisbr** [comment]
Yes sure! We can add as a predefined formatter. We just need a name, any suggestion?

**Comment by KronosTheLate** [comment]
That is a tough one...
possibly `nomissing` and `nonothing` for the individual cases. And `nomissingnonothing` and `nonothingnomissing` (so 2 formatters, where one simply calls the other) for the combined case? It is ugly, but clear, and possible to remember.

Other suggestions are obviously very welcome xD

**Comment by ronisbr** [comment]
`ft_nomissing` and `ft_nonothing` seems fine. The combined action can be achieved by using both at the same time.

**Comment by KronosTheLate** [comment]
Amazing! Works like a charm:
```julia
julia> using PrettyTables

julia> data = [1 2 missing
       4 missing nothing
       nothing 8 9]
3×3 Matrix{Union{Missing, Nothing, Int64}}:
 1         2          missing
 4          missing   nothing
  nothing  8         9

julia> pretty_table(data, formatters=(ft_nomissing))
┌─────────┬────────┬─────────┐
│  Col. 1 │ Col. 2 │  Col. 3 │
├─────────┼────────┼─────────┤
│       1 │      2 │         │
│       4 │        │ nothing │
│ nothing │      8 │       9 │
└─────────┴────────┴─────────┘

julia> pretty_table(data, formatters=(ft_nonothing))
┌────────┬─────────┬─────────┐
│ Col. 1 │  Col. 2 │  Col. 3 │
├────────┼─────────┼─────────┤
│      1 │       2 │ missing │
│      4 │ missing │         │
│        │       8 │       9 │
└────────┴─────────┴─────────┘

julia> pretty_table(data, formatters=(ft_nonothing, ft_nomissing))
┌────────┬────────┬────────┐
│ Col. 1 │ Col. 2 │ Col. 3 │
├────────┼────────┼────────┤
│      1 │      2 │        │
│      4 │        │        │
│        │      8 │      9 │
└────────┴────────┴────────┘
```
