### ISSUE TITLE
`tf_dataframe` is missing from predefined_formats

### ISSUE THREAD

**Issue by YongHee-Kim** [ronisbr/PrettyTables.jl#155]
https://github.com/ronisbr/PrettyTables.jl/blob/3447e26d931bfd2d165c88508892801f3567cda0/docs/src/man/text_backend.md?plain=1#L472

is removed from this commit https://github.com/ronisbr/PrettyTables.jl/commit/24aa1203ccafef7925ac1ce048a2714ee3375bf9#diff-cd207b492fd17d905c8bef91f32da15212ca4c7195f8c68f4ad9eb657c1f80d7 

shoud we modify the doc to reflect this change?

**Comment by ronisbr** [comment]
Hi @YongHee-Kim 

Nice catch! Yes, we should remove from the docs. This format was the old one used by DataFrames. When PrettyTables became its backend, I removed this table format.
