### ISSUE TITLE
printing empty tables

### ISSUE THREAD

**Issue by xitology** [ronisbr/PrettyTables.jl#156]
Happy New Year!

When the input table has no rows, I think it would be useful if PrettyTable could still display the table header.  Currently, it either prints nothing or raises an error depending on the layout of the table:
```julia
julia> zeros(0, 2) |> pretty_table

julia> (x = Int[], y = Int[]) |> pretty_table

julia> @NamedTuple{x::Int, y::Int}[] |> pretty_table
ERROR: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at ~/src/julia/usr/share/julia/base/range.jl:873
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at ~/src/julia/usr/share/julia/base/range.jl:873
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at ~/src/julia/usr/share/julia/base/dict.jl:712
  ...
Stacktrace:
 [1] indexed_iterate(I::Nothing, i::Int64)
   @ Base ./tuple.jl:91
 [2] _preprocess_Tables_row(data::Vector{NamedTuple{(:x, :y), Tuple{Int64, Int64}}}, header::Nothing)
   @ PrettyTables ~/.julia/packages/PrettyTables/nQZHQ/src/private.jl:107
 [3] #_pretty_table#80
   @ ~/.julia/packages/PrettyTables/nQZHQ/src/private.jl:364 [inlined]
 [4] _pretty_table
   @ ~/.julia/packages/PrettyTables/nQZHQ/src/private.jl:360 [inlined]
 [5] #pretty_table#68
   @ ~/.julia/packages/PrettyTables/nQZHQ/src/print.jl:706 [inlined]
 [6] pretty_table
   @ ~/.julia/packages/PrettyTables/nQZHQ/src/print.jl:705 [inlined]
 [7] |>(x::Vector{NamedTuple{(:x, :y), Tuple{Int64, Int64}}}, f::typeof(pretty_table))
   @ Base ./operators.jl:959
 [8] top-level scope
   @ REPL[43]:1
```

**Comment by ronisbr** [comment]
Hi @xitology !

Happy new year!

I will think about it because it might have some edge cases that we need to figure out what to do. The biggest problem is that the algorithm (especially for the text backend) is very dependent on the number of rows. I think I can bypass it but I am not sure how much work it will take. For HTML and LaTeX, It should be very simple.

**Comment by bkamins** [comment]
Yes - it would be good to fix these at some point.
Having an empty table that is later populated in a loop is a common pattern.

**Comment by ronisbr** [comment]
Hi @xitology and @bkamins !

Should I treat this issue as a bug, which means I will add in v2.1.3, or a new feature, which means I will add in v2.2?

**Comment by xitology** [comment]
> Hi @xitology and @bkamins !
> 
> Should I treat this issue as a bug, which means I will add in v2.1.3, or a new feature, which means I will add in v2.2?

With respect to semantic versioning, it is a new feature, IMO.

**Comment by bkamins** [comment]
Yes - I would go for v2.2 also

**Comment by ronisbr** [comment]
Ok!

@xitology 

By the way, the following will continue to fail:

```julia
julia> @NamedTuple{x::Int, y::Int}[] |> pretty_table
```

The problem is with Tables.jl interface. I need to fetch the first row to get the column names:

```julia
julia> a = @NamedTuple{x::Int, y::Int}[]
NamedTuple{(:x, :y), Tuple{Int64, Int64}}[]

julia> Tables.rows(a) |> first
ERROR: BoundsError: attempt to access 0-element Vector{NamedTuple{(:x, :y), Tuple{Int64, Int64}}} at index [1]
Stacktrace:
 [1] getindex
   @ ./array.jl:924 [inlined]
 [2] first
   @ ./abstractarray.jl:404 [inlined]
 [3] |>(x::Vector{NamedTuple{(:x, :y), Tuple{Int64, Int64}}}, f::typeof(first))
   @ Base ./operators.jl:911
 [4] top-level scope
   @ REPL[168]:1
```

I have no idea what to do in this case.

**Comment by bkamins** [comment]
You do not need a first row. I would propose to use `Tables.schema` if table has zero rows. Now it can be `nothing`, in which case I would drop printing names and eltypes (as is currently done) but if it is not `nothing` then you have all information you need:

```
julia> Tables.schema(@NamedTuple{x::Int, y::String}[])
Tables.Schema:
 :x  Int64
 :y  String

julia> Tables.schema(DataFrame(@NamedTuple{x::Int, y::String}[]))
Tables.Schema:
 :x  Int64
 :y  String
```

**Comment by bkamins** [comment]
`nothing` is returned in schema-less tables, in which case, if they have 0 rows, you cannot do anything.

**Comment by ronisbr** [comment]
Thanks @bkamins ! I will fix it also.

**Comment by ronisbr** [comment]
I pushed the code to print tables with no rows/columns, but without this fix related to Tables.jl. Can you please test ?

**Comment by bkamins** [comment]
In what PR/branch do you have it?

**Comment by bkamins** [comment]
I tested `master` branch. Looks good:
```
julia> using DataFrames

julia> DataFrame()
0×0 DataFrame

julia> DataFrame(a=[])
0×1 DataFrame
 Row │ a
     │ Any
─────┴─────

julia> DataFrame(a=[], b=Int[])
0×2 DataFrame
 Row │ a    b
     │ Any  Int64
─────┴────────────

julia> DataFrame(rand(0, 100), :auto)
0×100 DataFrame
 Row │ x1       x2       x3       x4       x5       x6       x7       x8       x9       x10      x11      x12      x13      x14      x15      x16      x17      x18      ⋯
     │ Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  ⋯
─────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                                        82 columns omitted
```
and
![image](https://user-images.githubusercontent.com/6187170/195946787-64bb7eab-9d78-44fd-bfec-b11aed5d7444.png)

**Comment by ronisbr** [comment]
Done! After the amazing suggestion of @bkamins, now we have:

```julia
julia> a = @NamedTuple{x::Int, y::Int}[]
NamedTuple{(:x, :y), Tuple{Int64, Int64}}[]

julia> pretty_table(a)
┌───────┬───────┐
│     x │     y │
│ Int64 │ Int64 │
└───────┴───────┘
```

**Comment by bkamins** [comment]
@ronisbr in https://github.com/ronisbr/PrettyTables.jl/commit/05a1567ff8eb6862a1659236608d9c522bd28ada#diff-4cbc6b02eb6507d8a46a68c884d773f031e19fbf2d1a241e2019c50d1453efa9R125
instead of:
```
[sch.names...]
```
I think that more idiomatic would be:
```
collect(Symbol, sch.names)
```
(just like you do in line 115)

But this is a minor thing. It is just a bit safer and faster as you specify target element type and do not splat.

**Comment by ronisbr** [comment]
Hi @bkamins !

I totally missed this amazing comment. I will fix it.

Some parts of PrettyTables are very old and definitely needs some clean-up :D

**Comment by ronisbr** [comment]
The new version now supports this feature!
