### ISSUE TITLE
Row headers

### ISSUE THREAD

**Issue by GregPlowman** [ronisbr/PrettyTables.jl#158]
Column headers can be printed using the `header` keyword argument.
Could there be something similar for row headers (i.e. the first column), say `row_header`?

**Comment by ronisbr** [comment]
Hi @GregPlowman !

Is the keyword `row_names` what you are looking for?

**Comment by GregPlowman** [comment]
Yes!! Exactly what I was looking for.
Sorry, I was looking at stable docs, rather than dev docs.

Is there a `row_names_crayon` or similar, equivalent to `header_crayon`?

**Comment by ronisbr** [comment]
Perfect!

Yes, the option is called `row_name_crayon`. Is it working?

**Comment by GregPlowman** [comment]
Bingo! `row_name_crayon` works.
(I had tried variations such as `row_names_crayon` and `row_names_header_crayon` similar to `rownum_header_crayon`)
Thanks for your help and patience!

**Comment by ronisbr** [comment]
Awesome! And I agree that we need to standardize the names here :D I will take the next major version (which will be highly breaking) to address this.
