### ISSUE TITLE
Keyword arguments: change `noheader=true` -> `header=false` ?

### ISSUE THREAD

**Issue by ericphanson** [ronisbr/PrettyTables.jl#160]
This might just be my pet peeve, but I get annoyed by `nosubheader=true`; in my opinion, it's more direct as `subheader=false`. I think the only keyword arguments starting with `no` are `nosubheader` and `noheader`. I think these should be `header` and `subheader` instead, or `print_header`, `print_subheader` if you want to distinguish with passing a header row.

I bring this up only because it sounds like there might be a breaking release soon (https://discourse.julialang.org/t/help-testing-prettytables-v2/76752).

**Comment by ronisbr** [comment]
Hi @ericphanson 

I complete agree! Choosing `header = false` is bad because you use `header` now to pass the header. Hence, it will require a Union that might slow things. How about `show_header` and `show_subheader`?

**Comment by ericphanson** [comment]
Sure, those sound good to me!

**Comment by ronisbr** [comment]
Done! Thank you very much @ericphanson to pointing this out. It is muuuuuch better now :) Btw, the old keywords will work but are marked as deprecated.

**Comment by ericphanson** [comment]
thank you!
