### ISSUE TITLE
stacked cells

### ISSUE THREAD

**Issue by tbeason** [ronisbr/PrettyTables.jl#163]
Do you have any suggestions for how one might go about simply generating a table where each column is actually 2 tables or matrices interleaved or interwoven? I have in mind something like https://github.com/jmboehm/RegressionTables.jl but simpler.

For example, if matrix `A` holds my model coefficients and matrix `B` holds their standard errors (so `A` and `B` are the same size), how can I print a table where the coefficient appears with the standard error below it in parentheses? This is what I mean when I say "stacked cell".

**Comment by ronisbr** [comment]
Hi @tbeason !

Hum, one "hacky" way is to provide a formatter with a closure (matrix B) that will convert the value in matrix A to string, and create a string with a break line. Then, you can render the table using `linebreaks = true`.

```julia
function test(A, B)
    formatter = (v, i, j) -> begin
        return """
            $(round(v, digits = 3))
            ($(round(B[i, j], digits = 3)))"""
       end

    pretty_table(
        A;
        formatters = (formatter,),
        linebreaks = true,
        vlines = :none
    )
end
```

```julia
julia> test(rand(3,3), rand(3,3) * 0.01)
───────────────────────────
  Col. 1   Col. 2   Col. 3
───────────────────────────
   0.259    0.146    0.494
 (0.006)  (0.002)  (0.009)
   0.122     0.45    0.541
 (0.009)  (0.006)  (0.004)
   0.873    0.768    0.195
 (0.008)  (0.007)  (0.003)
───────────────────────────
```

You can also align everything at the dot:

```Julia
function test(A, B)
    formatter = (v, i, j) -> begin
        return """
            $(round(v, digits = 3))
            ($(round(B[i, j], digits = 3)))"""
       end

    pretty_table(
        A;
        alignment_anchor_regex = Dict(0 => [r"\."]),
        formatters = (formatter,),
        linebreaks = true,
        vlines = :none
    )
end
```

```julia
julia> test(rand(3,3), rand(3,3) * 0.01)
───────────────────────────
  Col. 1   Col. 2   Col. 3
───────────────────────────
  0.575    0.459    0.085
 (0.002)  (0.006)  (0.002)
  0.701    0.156    0.711
 (0.002)  (0.007)  (0.003)
  0.82     0.758    0.567
 (0.006)  (0.009)  (0.006)
───────────────────────────
```

**Comment by tbeason** [comment]
I think that might just work! I will let you know the outcome. I'll set a reminder for myself to close this issue in a few days if I don't need any additional help.

**Comment by ronisbr** [comment]
Perfect!
