### ISSUE TITLE
LaTeX Backend: Captions

### ISSUE THREAD

**Issue by BeastyBlacksmith** [ronisbr/PrettyTables.jl#164]
is it possible to add captions and labels to tables in the LaTeX Backend?

**Comment by ronisbr** [comment]
Hi @BeastyBlacksmith !

Yes! You can use the `label` and `title` option, but they only work if you wrap the table inside an environment:

```julia
julia> pretty_table(rand(3, 3), backend = :latex, label = "tab:table_1", title = "Table caption", wrap_table = true)
\begin{table}
  \caption{Table caption}
  \begin{tabular}{rrr}
    \hline\hline
    \textbf{Col. 1} & \textbf{Col. 2} & \textbf{Col. 3} \\\hline
    0.830604 & 0.494624 & 0.98307 \\
    0.680341 & 0.899643 & 0.047398 \\
    0.298289 & 0.485772 & 0.232945 \\\hline\hline
  \end{tabular}
  \label{tab:table_1}
\end{table}
```

**Comment by BeastyBlacksmith** [comment]
Thanks, seems I missed that in the documentation. There is one other thing I am missing and this is constant width columns under alignment I can only find centred, left- and right-aligned.

**Comment by ronisbr** [comment]
Yes, we do not support constant width alignment yet here. I will think how can we do this.
