### ISSUE TITLE
Rich HTML output

### ISSUE THREAD

**Issue by lorenzoh** [ronisbr/PrettyTables.jl#166]
Is it possible currently to render individual cells with custom HTML output when using the HTML backend?

As I understand it, currently cell contents are either always escaped when using the HTML backend, or not at all when passing `allow_html_in_cells = true`. I think it would be helpful for building nice HTML tables, if you could specify that some cells should not be escaped, similarly to how `AnsiTextCell` does not escape ANSI escape sequences.

The design I am proposing looks as follows and closely resembles the API of `AnsiTextCell`.

currently, this does not embed an HTML element, even though `HTML` has a `show` definition for mimetype `text/html`:

```julia
pretty_table(HTML, [1, 2, Base.HTML("<strong>3</strong>")])
```

The proposal is to add a `HTMLCell` wrapper for elements of the table data that will
- disable HTML escaping (i.e. accept raw HTML when passed a string); and
- for rich objects other than strings, e.g. `Base.HTML`, try to use the `show(io, ::MIME("text/html"), ::T)` method to render them as HTML

So for the above we would write:

```julia
pretty_table(HTML, [1, 2, HTMLCell("<strong>3</strong>")])  # string passed to HTMLCell is interpreted as raw HTML
```

And custom types with the appropriate `show` method should be rendered using that as well:

```julia
struct A end
Base.show(io::IO, ::MIME"text/html", ::A) = print(io, "<strong>CustomPrinting</strong>")
```

---

Do you think it makes sense to support this feature? What do you think of the proposed user-facing API?

**Comment by ronisbr** [comment]
Hi @lorenzoh !

Yes, this request is very important. I am doing something very similar in LaTeX backend, where you can use the type `LatexCell` to input raw latex commands. Maybe we can just create a `HtmlCell` here and drop the option `allow_html_in_cells` to keep consistency among the backends. Do you agree with this proposal?

**Comment by lorenzoh** [comment]
Yeah, that sounds good!
