### ISSUE TITLE
option to render new lines normally in HTML

### ISSUE THREAD

**Issue by ExpandingMan** [ronisbr/PrettyTables.jl#167]
I needed to display a log via HTML and I found that PrettyTables.jl is a great low-effort solution to that problem.

The only issue I am having is that some of my log messages are quite long and multiple line strings.  For the most part the rendering is nice, the browser knows how to fit it in the cell correctly and it looks pretty good, the only problem is that instead of printing line breaks it prints them as `\n`.  It inserts its own linebreaks when the lines are too long (I assume this happens when the browser renders), but I'd really like it to retain the original line breaks.  Presumably this is possible without breaking the HTML cells.

Oddly, it does not seem to matter whether I pass `renderer=:print` or `renderer=:show` so I assume something a little more complicated is going on there, so it may not be such a simple fix.

**Comment by ExpandingMan** [comment]
I think an issue on my end caused me to think that `linebreak=true` doesn't work when it does... I'll figure it out and report back...

**Comment by ronisbr** [comment]
Perfect! I am glad it worked for you :)
