### ISSUE TITLE
Print all rows?

### ISSUE THREAD

**Issue by binyamink** [ronisbr/PrettyTables.jl#17]
Hi, thanks for the great package. Is there an option to print all rows in a very long table?

**Comment by ronisbr** [comment]
Hi @binyamink 

Thanks :) I think you are printing with the default parameters to your screen. In this case, crop mode is selected to fit the table into the screen. What you can do is to pass the option `crop = :none` or `crop = :horizontal`. In the first case the entire table will be printed. In the second case the table will only be cropped horizontally. Can you please tell me it this worked?

**Comment by binyamink** [comment]
sorry for the delay - yeah that work, thanks a lot!

**Comment by ronisbr** [comment]
Good! :)
