### ISSUE TITLE
HTML Output

### ISSUE THREAD

**Issue by bkamins** [ronisbr/PrettyTables.jl#184]
@ronisbr consider this example:
![image](https://user-images.githubusercontent.com/6187170/193872191-b454fe17-a175-4221-bd4d-bf03becd6cd9.png)

Note that we omit printing row 14 but replace it with vertical dots. So equally well we could have just printed it.

**Comment by bkamins** [comment]
Reproducer is in https://github.com/bkamins/DataFrames-Showcase, file bison.ipynb

**Comment by ronisbr** [comment]
Yes, this is a bug. I probably used a `<` instead of a `<=` somewhere. I will investigate.

**Comment by ronisbr** [comment]
Hi @bkamins !

I do not now what to do here. You are asking in this example to show 25 data rows. Hence, PrettyTables is showing 25 data rows, but it needs 1 additional row to add the continuation line. If we modify this behavior, it might be a little confusing, because you will ask it to show 25 data rows, but 26 will be printed.

**Comment by ronisbr** [comment]
Like here:

<img width="1098" alt="Captura de Tela 2022-10-14 às 12 23 38" src="https://user-images.githubusercontent.com/1068295/195883341-719e7e14-a32c-40ce-abc3-3a3e5f3c9392.png">

**Comment by ronisbr** [comment]
My suggestion is:

Since this will require modify the behavior of `max_num_of_rows` in a way it might be confusing, if you want, we can fix this inside DataFrames. If the number of hidden rows is 1, we just show everything.

**Comment by bkamins** [comment]
We can drop this requirement. My understanding of:

> The maximum number of table rows that will be rendered.

was that it included the continuation line. However, I understand that you want not to count continuation line. In which case the current behavior is correct.

I am OK with whatever decision you make (if you want to keep things as is please close this issue)

**Comment by bkamins** [comment]
Let us leave it consistent. So nothing to do. Thank you!
