### ISSUE TITLE
text and HTML display of tables with no rows

### ISSUE THREAD

**Issue by bkamins** [ronisbr/PrettyTables.jl#187]
We currently have in HTML:
![image](https://user-images.githubusercontent.com/6187170/194116175-2ca76d48-cf7b-4660-9a27-c881153c89f1.png)

The same in text/plain:
```
julia> select(DataFrame(), nrow)
0×1 DataFrame
```

Is this intended? I would expect header to be printed.

**Comment by ronisbr** [comment]
Yes, we just skip everything if there is no rows. We can modify it, but it will take significant modifications inside PrettyTables to allow printing the header in matrices without rows.

**Comment by bkamins** [comment]
I would propose to add it as "to do" in the long run. The point is that it is important to be able see what column names and types a table has even if it does not have any rows.

BTW: why is it complicated?

**Comment by ronisbr** [comment]
It is not complicated at all. It is just a lot of changes. In many places I always assumed that the number of rows cannot be 0. Hence, I just need to pass through all the backends doing the modifications. There are also some behaviors we need to decide in text backend. For example, when there are no rows, but the format asks for a horizontal line after the header and at the bottom of the table, what should we do? Furthermore, the header horizontal line is not an "end" line. Thus, the output should be a little strange if I just print the header:

```
0×2 DataFrame
 Row │ A      B
     │ Int64  String
─────┼───────────────
```

**Comment by bkamins** [comment]
I understand it could be a lot of work and many tiny decisions. For this reason there is no rush. But I would recommend to put it on a to-do list.

> For example, when there are no rows, but the format asks for a horizontal line after the header and at the bottom of the table, what should we do?

I think it should be:
```
0×2 DataFrame
 Row │ A      B
     │ Int64  String
─────┼───────────────
─────┼───────────────
```
and it would seem normal to me

**Comment by ronisbr** [comment]
I did not understand. In DataFrames format, we only have one horizontal line.

**Comment by bkamins** [comment]
Yes - but you asked what should happen if someone additionally asks for another line at the bottom.
By default in DataFrames.jl the output should be just as you have presented in https://github.com/ronisbr/PrettyTables.jl/issues/187#issuecomment-1269137590

**Comment by ronisbr** [comment]
Ah! Ok! Perfect :)

**Comment by ronisbr** [comment]
Dup #156
