### ISSUE TITLE
Centring on decimal separator

### ISSUE THREAD

**Issue by CiaranOMara** [ronisbr/PrettyTables.jl#189]
There is a Unicode character 'FIGURE SPACE' (U+2007, `&#8199;`). That character may provide a solution for centring different fonts on a decimal separator.

https://github.com/JuliaData/DataFrames.jl/pull/3096

**Comment by ronisbr** [comment]
Thanks @CiaranOMara !

What I does not understand is how to treat numbers that have different widths in non-monospace fonts. For example:

1111111111
0000000000

Both lines have 10 numbers.

**Comment by CiaranOMara** [comment]
Oh, that's annoying. I thought a font's numeric characters had the same width, and the purpose of the figure/numeric space was to facilitate grouping in precisely this type of scenario.

**Comment by ronisbr** [comment]
The only way to get this is by using `monospaced` fonts. However, nobody liked the idea to use monospace fonts in HTML printing. :)
