### ISSUE TITLE
In Latex, a way to make the header not bold?

### ISSUE THREAD

**Issue by pdeffebach** [ronisbr/PrettyTables.jl#197]
Can't seem to find a way to do this. There is a struct containing the field `header_envs`, but it seems like I can't modify that as an option.

**Comment by pdeffebach** [comment]
Nevermind! An empty `String` vector `String[]` works!

**Comment by ronisbr** [comment]
Nice! Yes, you need to pass a vector of strings :)

**Comment by likanzhan** [comment]
Hi, @pdeffebach. I got the same problem, and I'm not quite clear how you acheive this. Could you provide an simple example so that I can follow? Thank you very much. Likan

**Comment by likanzhan** [comment]
Thank you very much, @ronisbr !
