### ISSUE TITLE
Function that returns the table as string

### ISSUE THREAD

**Issue by darrencl** [ronisbr/PrettyTables.jl#20]
First of all, thanks for the awesome package!

I'm currently writing an app that writes a report at the end of the process. To achieve this, I'm constructing the message, so I can print them all at once at the end. Inside the message, I'd like to print pretty_table, so I would need to get a string returned from `pretty_table` function (which currently returns `nothing`). 

```
msg = "some msg"
...
msg *= "pretty table here"
msg *= "additional msg"
println(msg)
``` 
Of course I can separate the prints, but I think it would be great to be able to get the `pretty_tables`'s raw string. Another use case that I can think of is putting the output string (with this pretty table in it) into a file. 

I'm happy to submit a PR if you can point out the best way to make this.

**Comment by ronisbr** [comment]
Hi @darrencl !

Thanks for the bug report. This should be very easy to do. However, it is already possible using a custom `IOBuffer`:

```Julia
julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> pretty_table(io,rand(3,3))

julia> str = String(take!(io))
"┌─────────────────────┬─────────────────────┬────────────────────┐\n│              Col. 1 │              Col. 2 │             Col. 3 │\n├─────────────────────┼─────────────────────┼────────────────────┤\n│ 0.10490658965307231 │ 0.02972409244573715 │ 0.2748083487060262 │\n│  0.7899267747304952 │  0.8216407089124966 │ 0.8549614515104658 │\n│  0.3071710195523847 │ 0.09385538226603929 │ 0.3647755708295213 │\n└─────────────────────┴─────────────────────┴────────────────────┘\n"
```

Do you think this is enough or should be add a new function that returns the string?

**Comment by darrencl** [comment]
Ah, thank you @ronisbr ! That should be easy enough. I'll close the issue then.
