### ISSUE TITLE
Setting maximum column width

### ISSUE THREAD

**Issue by darrencl** [ronisbr/PrettyTables.jl#21]
Hi @ronisbr ,

I am just wondering if it is possible to setting maximum column width (`max_colwidth`) with the current version? If not, I think it would be great to have one. While `screen_size` option takes the maximum character of the printed table itself, this option can set the maximum character in a column. This is similar on what [`pandas.options`](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html) has by setting in `display.max_colwidth`.

Another relevant feature, which maybe useful, is user can specify the behavior when the column exceeds `max_colwidth`. With this, the user will be able to choose between crop (`...` on remaining characters), or split with new line, that is split the remaining character into new line (maybe split in closest whitespace). The latter is now possible to do with manual work on adding `\n` in string with `linebreaks=true`.

These options are useful for particularly printing long text data in tabular form.

Thanks

**Comment by ronisbr** [comment]
Hi @darrencl ,

Sorry for the late response, it was a very busy week.

I really like your suggestion. I will split this into two parts: it is easy to create the cropping based on the maximum column width. However, the automatic line break needs more thinking. We can split in the closest whitespace (adding `\n`), but this will lead to problems if a word is bigger than the column size. It should be "easy" to create an algorithm that deals with all of it, but I will need sometime to think about it.

**Comment by darrencl** [comment]
Hi @ronisbr 

No worries at all! Thanks for getting back to this.

I agree on splitting this into 2 parts given the latter feature, I think, is more of 'nice to have'. 

Yeah, I was thinking the same on splitting the string into closest whitespace and maybe adding spaces if the number of character is less than the max (with this, every line will have same number of characters). If I understand the default behavior correctly, this will ensure every columns have the same width. In regards to the issues on `length(word) > max_colwidth`, I think we have 2 options: throwing an `Exception` (maybe `StringIndexError`?), or warn user and _auto-update_ `max_colwidth = length(word_exceeding)`. I kind of leaning towards the latter as it sounds more robust and more flexible.

**Comment by ronisbr** [comment]
Hi @darrencl ,

If you use `master`, then you can use the keyword `column_width` to select the column size of each column. Can you test please?

```julia
julia> model = [1.123456789 for i = 1:8, j = 1:10];

julia> pretty_table(model; columns_width = [1, 0, 2, 3, 4, 5, 6, 7, 8, 9])
┌───┬─────────────┬────┬─────┬──────┬───────┬────────┬─────────┬──────────┬───────────┐
│ … │      Col. 2 │ C… │ Co… │ Col… │ Col.… │ Col. 7 │  Col. 8 │   Col. 9 │   Col. 10 │
├───┼─────────────┼────┼─────┼──────┼───────┼────────┼─────────┼──────────┼───────────┤
│ … │ 1.123456789 │ 1… │ 1.… │ 1.1… │ 1.12… │ 1.123… │ 1.1234… │ 1.12345… │ 1.123456… │
│ … │ 1.123456789 │ 1… │ 1.… │ 1.1… │ 1.12… │ 1.123… │ 1.1234… │ 1.12345… │ 1.123456… │
│ … │ 1.123456789 │ 1… │ 1.… │ 1.1… │ 1.12… │ 1.123… │ 1.1234… │ 1.12345… │ 1.123456… │
│ … │ 1.123456789 │ 1… │ 1.… │ 1.1… │ 1.12… │ 1.123… │ 1.1234… │ 1.12345… │ 1.123456… │
│ … │ 1.123456789 │ 1… │ 1.… │ 1.1… │ 1.12… │ 1.123… │ 1.1234… │ 1.12345… │ 1.123456… │
│ … │ 1.123456789 │ 1… │ 1.… │ 1.1… │ 1.12… │ 1.123… │ 1.1234… │ 1.12345… │ 1.123456… │
│ … │ 1.123456789 │ 1… │ 1.… │ 1.1… │ 1.12… │ 1.123… │ 1.1234… │ 1.12345… │ 1.123456… │
│ … │ 1.123456789 │ 1… │ 1.… │ 1.1… │ 1.12… │ 1.123… │ 1.1234… │ 1.12345… │ 1.123456… │
└───┴─────────────┴────┴─────┴──────┴───────┴────────┴─────────┴──────────┴───────────┘
```

**Comment by darrencl** [comment]
Hi @ronisbr ,

Sorry for the late reply, was busy yesterday.
Just tested it and working as expected! Very nice!

I think an option to input `column_width` as `int` can be added as opposed to only restricting it to be a list. This way, the users can conveniently use `int` to set the same `column_width` across the table.

**Comment by ronisbr** [comment]
Nice! The idea of an `Int` is perfect! I will do that :)

**Comment by ronisbr** [comment]
What do you think about removing the possibility to be `nothing` and by default I make this parameter equal 0. This will lead to all columns to have their size automatically computed and we can also specify a fixed size for all of them.

**Comment by darrencl** [comment]
I think it is not a big deal since the automatic size is the default behaviour. :)
I assume the users will only specify the `column_width` when they need it anyway, i.e. `> 0`.

**Comment by ronisbr** [comment]
Done!

```julia
julia> model = [1.123456789 for i = 1:8, j = 1:10];

julia> pretty_table(model; columns_width = 5)
┌───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ Col.… │ Col.… │ Col.… │ Col.… │ Col.… │ Col.… │ Col.… │ Col.… │ Col.… │ Col.… │
├───────┼───────┼───────┼───────┼───────┼───────┼───────┼───────┼───────┼───────┤
│ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │
│ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │
│ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │
│ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │
│ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │
│ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │
│ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │
│ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │ 1.12… │
└───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘
```

**Comment by ronisbr** [comment]
Hi @darrencl !

Finally, I could finish the code to auto wrap the text on spaces. Can you please test to me? Is it available in `master`. The option is `autowrap`, but it only works if `linebreaks` is true and the column width is fixed. This was somewhat complicated and I am expecting regressions and bugs.

```
julia> pretty_table( ["this is a very very long line\nand another very very very long line" 10 20;
                      "Here is another line\nbut not so long" 30 40]; autowrap = true, linebreaks = true, columns_width = [10,-1,-1], hlines = 1:2 )
┌────────────┬────────┬────────┐
│     Col. 1 │ Col. 2 │ Col. 3 │
├────────────┼────────┼────────┤
│  this is a │     10 │     20 │
│  very very │        │        │
│       long │        │        │
│       line │        │        │
│        and │        │        │
│    another │        │        │
│  very very │        │        │
│  very long │        │        │
│       line │        │        │
├────────────┼────────┼────────┤
│    Here is │     30 │     40 │
│    another │        │        │
│       line │        │        │
│    but not │        │        │
│         so │        │        │
│       long │        │        │
└────────────┴────────┴────────┘

julia> pretty_table( ["this is a very very long line\nand another very very very long line" 10 20;
                      "Here is another line\nbut not so long" 30 40]; autowrap = true, linebreaks = true, columns_width = [10,-1,-1], hlines = 1:2, alignment = :c )
┌────────────┬────────┬────────┐
│   Col. 1   │ Col. 2 │ Col. 3 │
├────────────┼────────┼────────┤
│ this is a  │   10   │   20   │
│ very very  │        │        │
│    long    │        │        │
│    line    │        │        │
│    and     │        │        │
│  another   │        │        │
│ very very  │        │        │
│ very long  │        │        │
│    line    │        │        │
├────────────┼────────┼────────┤
│  Here is   │   30   │   40   │
│  another   │        │        │
│    line    │        │        │
│  but not   │        │        │
│     so     │        │        │
│    long    │        │        │
└────────────┴────────┴────────┘
```

**Comment by ronisbr** [comment]
In fact I just found a bug :D

**Comment by ronisbr** [comment]
No its fine :)

```
julia> pretty_table( ["this is a very very long line\nand another very very very long line" 10 20;
                      "Here is another line\nbut not so long" 30 40]; autowrap = true, linebreaks = true, columns_width = [10,-1,-1], hlines = 1:2 )
┌────────────┬────────┬────────┐
│     Col. 1 │ Col. 2 │ Col. 3 │
├────────────┼────────┼────────┤
│  this is a │     10 │     20 │
│  very very │        │        │
│  long line │        │        │
│        and │        │        │
│    another │        │        │
│  very very │        │        │
│  very long │        │        │
│       line │        │        │
├────────────┼────────┼────────┤
│    Here is │     30 │     40 │
│    another │        │        │
│       line │        │        │
│    but not │        │        │
│    so long │        │        │
└────────────┴────────┴────────┘

julia> pretty_table( ["this is a very very long line\nand another very very very long line" 10 20;
                      "Here is another line\nbut not so long" 30 40]; autowrap = true, linebreaks = true, columns_width = [10,-1,-1], hlines = 1:2, alignment = :c )
┌────────────┬────────┬────────┐
│   Col. 1   │ Col. 2 │ Col. 3 │
├────────────┼────────┼────────┤
│ this is a  │   10   │   20   │
│ very very  │        │        │
│ long line  │        │        │
│    and     │        │        │
│  another   │        │        │
│ very very  │        │        │
│ very long  │        │        │
│    line    │        │        │
├────────────┼────────┼────────┤
│  Here is   │   30   │   40   │
│  another   │        │        │
│    line    │        │        │
│  but not   │        │        │
│  so long   │        │        │
└────────────┴────────┴────────┘
```

**Comment by darrencl** [comment]
@ronisbr Very nice! Thanks for the update!

**Comment by Jo-Fleck** [comment]
@ronisbr Thanks for this great package! 

Is column width control also supported for the tex backend? (I have in mind fixed width column-types such as shown [here](https://texblog.org/2019/06/03/control-the-width-of-table-columns-tabular-in-latex/).)

**Comment by ronisbr** [comment]
Hi @Jo-Fleck !

Thanks! I am glad it is being useful :)

Unfortunately the LaTeX backend does not support yet fixed columns. It is a very simple thing to implement, I just need to think about a good API.

**Comment by Jo-Fleck** [comment]
Thanks! I'll be happy to test and give feedback.
