### ISSUE TITLE
Remove dep on `Formatting.jl`?

### ISSUE THREAD

**Issue by haberdashPI** [ronisbr/PrettyTables.jl#210]
Given the somewhat [scary](https://github.com/JuliaIO/Formatting.jl/issues/71) [errors](https://github.com/JuliaIO/Formatting.jl/issues/108) one can get with `Formatting.jl` is there a good reason not to use the standard library `Printf` instead?

**Comment by ericphanson** [comment]
I think this is very concerning. PrettyTables is very widely used (e.g. by DataFrames) and this is the kind of thing that can cause papers to need to be retracted, delivered analyses to be incorrect, etc.

**Comment by ronisbr** [comment]
Done!

@haberdashPI thanks for the report!
@ericphanson thanks for the PR that fixed it! :)

**Comment by pdeffebach** [comment]
One reason: `Printf` doesn't allow the `%'0.2f` syntax, allowing for commas as thousands separator.  

So I would be supportive of moving back to Formatting.jl once their bug is fixed.

**Comment by haberdashPI** [comment]
Though it would be better if it were built in, can't this be solved with a
wrapper and clever application of `replace`?

**Comment by palday** [comment]
@pdeffebach @haberdashPI to the extent that we want that functionality, we could probably just migrate the relevant chunk of Formatting.jl, which is actually just wrapping Printf:

https://github.com/JuliaIO/Formatting.jl/blob/e4c9f60020e965a72abae049ddac7e02bf986067/README.md?plain=1#L139-L144

**Comment by ScottPJones** [comment]
Well, maybe you would consider moving to [Format.jl](https://github.com/JuliaString/Format.jl) 😄
I'm fixing the bugs and getting PRs that have been languishing in Formatting.jl ported and merged into Format.jl

**Comment by ronisbr** [comment]
Hi @ScottPJones !

That would be awesome! Are the bugs that started this thread fixed in Format.jl?

**Comment by ScottPJones** [comment]
@ronisbr I've fixed one of them (at the Hackathon 😄 ) and I'm working on the issue with the "e" format right now.
I'm also going to look at the rest of the PRs submitted to Formatting.jl, as they seem to be languishing there.
