### ISSUE TITLE
`header` is ignored for `Dict`

### ISSUE THREAD

**Issue by laborg** [ronisbr/PrettyTables.jl#212]
Hi,

I assumed that the header should show up when printing a Dict. Is this to be expected?

```julia-repl
julia> pretty_table(Dict(:a=>1,:b=>2),header=(["ColumnK","ColumV"]))
┌────────┬────────┐
│   Keys │ Values │
│ Symbol │  Int64 │
├────────┼────────┤
│      a │      1 │
│      b │      2 │
└────────┴────────┘
```
PrettyTables v2.2.6

**Comment by ronisbr** [comment]
Oops :) Thanks for the report! Should be fixed by now (when a new version is tagged).

**Comment by laborg** [comment]
wow, that was quick. thanks!
