### ISSUE TITLE
Rows are always omitted, despite max_num_of_rows=-1

### ISSUE THREAD

**Issue by maleadt** [ronisbr/PrettyTables.jl#214]
MWE:

```julia
julia> pretty_table(rand(1024); max_num_of_rows=-1)
┌────────────┐
│     Col. 1 │
├────────────┤
│   0.278362 │
│   0.343475 │
[snip]
│   0.793242 │
│     ⋮      │
└────────────┘
961 rows omitted
```

Reading the documentation, I would have thought that the (default setting of) `max_num_of_rows=-1` would have disabled row limiting:

> max_num_of_rows::Int: The maximum number of table rows that will be rendered. If it is lower than 0, then all rows will be rendered. (Default = -1)

Passing `io=stdout` (i.e. without the `IOContext` having `limit=true`) works around this, but I'd like to be able to keep using limited output for columns and cells, but not for rows, hence the use of `max_num_of_rows=-1`.

FWIW, this is on Julia 1.10, using PrettyTables v2.2.7.

**Comment by ronisbr** [comment]
Hi @maleadt !

Sorry, maybe we need to rewrite the documentation. `max_num_of_rows` contains the maximum number of rows that will be rendered (converted to string), which is not the same as the number of rows that will be printed. If you want to see all the rows in a display with limited size, you can use `crop = :none` or `crop = :horizontal`.

**Comment by maleadt** [comment]
Thanks!
