### ISSUE TITLE
How to cite this package?

### ISSUE THREAD

**Issue by juliohm** [ronisbr/PrettyTables.jl#218]
@ronisbr do you have a bibtext entry for it? Perhaps a Zenodo entry?

**Comment by ronisbr** [comment]
There is nothing yet. I have never heard about Zenodo, I will create an entry there and copy the link here!

**Comment by ronisbr** [comment]
Now we have a Zenodo entry :)

https://zenodo.org/doi/10.5281/zenodo.10015722

Thanks!
