### ISSUE TITLE
Add support for formatting Strings as in print() (not in a addition to repr())

### ISSUE THREAD

**Issue by GlenHertz** [ronisbr/PrettyTables.jl#22]
If a column of strings contains `"` characters then they are printed like:

```
func(\"temp\")
```
I'd like to be able to print the table as in `print`, like:

```
func("temp")
```

I typically use PrettyTables for viewing "publication" results (not debugging Julia strings) so I think `print` should be the default format for strings.  (Love this package, BTW.)

**Comment by ronisbr** [comment]
Hi @GlenHertz 

> If a column of strings contains `"` characters then they are printed like:
> 
> ```
> func(\"temp\")
> ```
> 
> I'd like to be able to print the table as in `print`, like:
> 
> ```
> func("temp")
> ```
> 
> I typically use PrettyTables for viewing "publication" results (not debugging Julia strings) so I think `print` should be the default format for strings.

I agree 100%! Indeed, this is a misunderstanding from my part about the function `escape_string`. Depending how you use it, it also scape the `"`, which we do not want. I will fix this today.

> (Love this package, BTW.)

Thanks! I'm glad it is being useful :)

**Comment by ronisbr** [comment]
Done! Can you please test @GlenHertz using `master`?

```julia
julia> matrix = [ 1 """
       function str(str = "one string")
           return str
       end"""
       2 """
       function str(str = "")
           if isempty(str)
               return "one string"
           else
               return str
           end
       end"""];

julia> pretty_table(matrix, alignment = :l, linebreaks = true)
┌────────┬──────────────────────────────────┐
│ Col. 1 │ Col. 2                           │
├────────┼──────────────────────────────────┤
│ 1      │ function str(str = "one string") │
│        │     return str                   │
│        │ end                              │
│ 2      │ function str(str = "")           │
│        │     if isempty(str)              │
│        │         return "one string"      │
│        │     else                         │
│        │         return str               │
│        │     end                          │
│        │ end                              │
└────────┴──────────────────────────────────┘
```

**Comment by GlenHertz** [comment]
I tested it and it works as desired, thanks!  I also ran it through my other code just to see if anything would break and it all works fine.

**Comment by ronisbr** [comment]
Perfect! Thanks for the feedback.
