### ISSUE TITLE
vlines: missing or wrongly documented option

### ISSUE THREAD

**Issue by bagohart** [ronisbr/PrettyTables.jl#221]
According to the doc:
```julia
vlines::Union{Nothing, Symbol, AbstractVector}: This variable controls where the vertical lines will be drawn. It can be nothing, :all, :none or a vector of integers. (Default = nothing)
[...]
the line after the header can be drawn by adding the symbol :header.
```
But this works:
```julia
pretty_table([1 2; 3 4],row_names=["lol","bla"];vlines=[:begin,:end,1],hlines=[:begin,:end,:header])
```
whereas this doesn't work:
```julia
pretty_table([1 2; 3 4],row_names=["lol","bla"];vlines=[:begin,:end,:header],hlines=[:begin,:end,:header])
```
failing with
```
ERROR: MethodError: Cannot `convert` an object of type Symbol to an object of type Int64
```
My impression is that this is just a copy and paste bug in the doc, but that feature also seems really useful, so maybe it's mistakenly not implemented or there is another symbol for `vlines` than for `hlines`? I tried to grep through the source code, but couldn't find any dedicated symbols, but I'm also pretty new to Julia, so maybe I just missed it.

**Comment by ronisbr** [comment]
Thanks @bagohart !

You are right. There is no meaning to have a `:header` in vertical lines. I will fix it.
