### ISSUE TITLE
Respect `alignment` when `tf = tf_markdown`

### ISSUE THREAD

**Issue by jakobjpeters** [ronisbr/PrettyTables.jl#222]
Currently, the generated markdown defaults to aligning right regardless of the alignment keyword. The markdown text is visually aligned correctly, but this does not hold after the markdown is rendered because the colon `:` symbol is not used in the `hline` to specify alignment.

```julia
julia> using PrettyTables, Markdown

julia> data = [1 2; 3 4];

julia> pretty_table(data, tf = tf_markdown, alignment = :l)
| Col. 1 | Col. 2 |
|--------|--------|
| 1      | 2      |
| 3      | 4      |

julia> Markdown.parse(pretty_table(String, data, tf = tf_markdown, alignment = :l))
  Col. 1 Col. 2
  –––––– ––––––
       1      2
       3      4
```

This feature would make it easier to copy (such as with `clipboard`) the markdown into other documents or render in the local environment (such as with `Markdown.parse`) without needing to edit the alignment manually.

**Comment by jakobjpeters** [comment]
duplicate of #67

**Comment by ronisbr** [comment]
Yeah, sorry about that :) I really need to implement a Markdown backend for those reasons...

**Comment by jakobjpeters** [comment]
All good! :)
