### ISSUE TITLE
Display SVG images in the table

### ISSUE THREAD

**Issue by mojaie** [ronisbr/PrettyTables.jl#225]
Thank you very much for your great effort for maintaining this library.

I'm working on displaying DataFrames with SVG images in Jupyter.
DataFrames seems not allow HTML inside cell, and I found a workaround of using markdown cells. Is this a intended behavior?

<img width="689" alt="スクリーンショット 2023-11-11 10 19 07" src="https://github.com/ronisbr/PrettyTables.jl/assets/1174134/1a6e8919-7b25-4aca-936d-0696fe1285b9">

**Comment by mojaie** [comment]
Perhaps this is more straightforward but but I wonder what the line break at the end is
<img width="804" alt="スクリーンショット 2023-11-12 9 51 46" src="https://github.com/ronisbr/PrettyTables.jl/assets/1174134/d09fda35-fb62-40b6-b011-dfaccb0cb2a2">

**Comment by ronisbr** [comment]
Hi @mojaie !

> DataFrames seems not allow HTML inside cell, and I found a workaround of using markdown cells. Is this an intended behavior?

Yes, it is! The purpose is to avoid breaking the table with HTML tags. Hence, we escape everything unless you explicitly say you want those tags. You have two options. The first is the one you found by setting `allow_html_in_cells`, the other is to wrap the cell content into a `HtmlCell` as stated here: https://ronisbr.github.io/PrettyTables.jl/stable/man/html_backend/

> Perhaps this is more straightforward but but I wonder what the line break at the end is

I have no ideia. Something is adding a break-line character when rendering the content. Can you please pass the option `linebreaks = true`?

**Comment by mojaie** [comment]
`linebreaks = true` did not work because my HTML code have SVG inside.

<img width="683" alt="スクリーンショット 2023-11-16 14 52 39" src="https://github.com/ronisbr/PrettyTables.jl/assets/1174134/e4e1d800-0e7c-4059-8cfb-4550e88aad86">

`HtmlCell` also produced the same output as shown in the `allow_html_in_cells` example above.
I found the HTML content have SVG and trailing `\n`  inside `<div>` so this would be escaped.

Anyway, markdown seems to work very well.
