### ISSUE TITLE
save PreettyTables

### ISSUE THREAD

**Issue by kulas2023** [ronisbr/PrettyTables.jl#227]
Is there a format (png or pdf) in which we can save the resulting table in color?

**Comment by ronisbr** [comment]
Hi @kulas2023,

Do you mean from the text back end (terminal)?

**Comment by kulas2023** [comment]
Exactly, I would like to save it as (pdf or png) in the form we obtained in the terminal. I would appreciate if you can help me.

**Comment by ronisbr** [comment]
This issue is duplicated (#213). Unfortunately, there is no way to support it. The best way is to take a screenshot of your terminal.
