### ISSUE TITLE
Error printing matrix of strings

### ISSUE THREAD

**Issue by rafael-guerra-www** [ronisbr/PrettyTables.jl#236]
Hello,

Please find here below a MWE that used to work in some earlier version of PrettyTables:
```
using PrettyTables

M = ["Base" "BenchmarkTools" "Core" "Crayons" "DelimitedFiles";
    "LinearAlgebra" "Pkg" "PrettyTables" "Random" "Statistics"
]
# this used to work, but now errors:
pretty_table(M, tf=tf_borderless, noheader=true, alignment=:l)
```
Is there a workaround?
Thank you.

**Comment by ronisbr** [comment]
Hi @rafael-guerra-www !

`noheader` was deprecated sometime ago. Please, change to `show_header = false`.
