### ISSUE TITLE
thousand separator

### ISSUE THREAD

**Issue by kafisatz** [ronisbr/PrettyTables.jl#239]
All, in the past I used "%'d" (with PrettyTables.jl) to show integers with a thousand separator.
However, this is not working anymore, see below.

Any idea how to fix this? 

```
julia> v=10000000000;PrettyTables.sprintf1("%d",v)
"10000000000"

julia> v=10000000000;PrettyTables.sprintf1("%'d",v)
ERROR: InvalidFormatStringError: ''' is not a valid type specifier
    "%'d"
     -^

Stacktrace:
 [1] Printf.Format(f::String)
   @ Printf C:\Users\bernhard\.julia\juliaup\julia-1.10.1+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Printf\src\Printf.jl:237
 [2] sprintf1(fmt::String, x::Int64)
   @ PrettyTables C:\Users\bernhard\.julia\packages\PrettyTables\E8rPJ\src\helpers.jl:150
 [3] top-level scope
   @ REPL[36]:1
```

**Comment by ronisbr** [comment]
Hi @kafisatz !

Unfortunately it is not possible anymore because we remove the dependency on Formatting.jl, see https://github.com/ronisbr/PrettyTables.jl/issues/210

The only way to accomplish it is to use some external package and a formatter.
