### ISSUE TITLE
Warning: DEPRECATION NOTICE of Formatting.jl

### ISSUE THREAD

**Issue by jmanthony3** [ronisbr/PrettyTables.jl#240]
While running some tests of a package I am developing with Julia v1.10.1 in VS Code on Windows 10, I was given the following warning suggesting to use another package instead of the allegedly outdated `Formatting.jl`. Running `]why Formatting` in a Julia-REPL shows `Formatting` to be a dependency of `PrettyTables`.

![image](https://github.com/JuliaData/DataFrames.jl/assets/62029937/9aa2bef9-42c8-4091-abd4-419e899f616b)

![image](https://github.com/JuliaData/DataFrames.jl/assets/62029937/e1a6e7d6-148b-4924-9da5-a9a98ada4d19)

**Comment by ronisbr** [comment]
Hi @jmanthony3 !

You are using an old version of PrettyTables.jl. We already removed this dependency.

**Comment by jmanthony3** [comment]
Classic "Did you turn it off and on again?" Well...no...,actually I did not run `]update` before posting this issue. Now updating and testing again the deprecation warning is gone.
