### ISSUE TITLE
Question: how to get `continuation_line` (⋮) when using `max_num_of_rows`

### ISSUE THREAD

**Issue by jonalm** [ronisbr/PrettyTables.jl#249]
For large tables `print_table` truncates the printed table and puts  `⋮` characters at the end of each column to indicate the truncation.  There seems to be some magic going on behind the scenes as this truncation is based on the size of the terminal. However, when I set `max_num_of_rows`  to a positive number, the truncation character `⋮` disappears. 

Is it a way to both select the maximum size of the printed rows, and append the truncation character if there are more rows in the table?

**Comment by jonalm** [comment]
Answering my own question: using the `display_size` keyword can be used to truncate with the continuation_line.

**Comment by ronisbr** [comment]
Hi @jonalm !

Awesome! I am in the middle of a full rewrite of PrettyTables.jl. I will introduce a lot of breaking changes, but also a lot of new features. The design will be much more simple to maintain (hopefully). In this case, you will be able to select how many rows or columns you want in text back end and the system will show the continuation line and columns.

For more information: https://discourse.julialang.org/t/current-state-and-the-future-of-prettytables-jl/118455
