### ISSUE TITLE
Align to decimal point by default

### ISSUE THREAD

**Issue by jariji** [ronisbr/PrettyTables.jl#254]
It would be easier to read tables if they were aligned to decimal point by default. Currently the order of magnitude represented by each column is inconsistent so it's hard to read. Of course I can customize it for each table, but it seems like a good default to me.

Current:
```jl
julia> pretty_table([(;a=1.0),(;a=1.23)])
┌─────────┐
│       a │
│ Float64 │
├─────────┤
│     1.0 │
│    1.23 │
└─────────┘
```
Proposed:

```jl
julia> pretty_table([(;a=1.0),(;a=1.23)])
┌─────────┐
│       a │
│ Float64 │
├─────────┤
│    1.00 │
│    1.23 │
└─────────┘
```

**Comment by ronisbr** [comment]
Hi @jariji 

You can already do this using the `alignment_anchor_regex`:

```Julia
julia> pretty_table([(;a=1.0),(;a=1.23)]; alignment_anchor_regex = Dict(0 => [r"\."]))
┌─────────┐
│       a │
│ Float64 │
├─────────┤
│    1.0  │
│    1.23 │
└─────────┘
```

**Comment by jariji** [comment]
Great, thanks. What do you think about doing this by default? I think that's what I'd normally want for a `Number` table.

**Comment by ronisbr** [comment]
I prefer to provide as few customization as possible by default and let the user decide. There are a lot of corner cases that will have a negative impact if we apply this alignment by default.
