### ISSUE TITLE
Getting the output as a string

### ISSUE THREAD

**Issue by aminya** [ronisbr/PrettyTables.jl#29]
I am trying to use PrettyTables as an HTML creator for Julia Table data types. For that, I need the `pretty_table` as a String.

I try this, but str is empty. 
```julia
using Suppressor
str = @capture_out(pretty_table(x, backend = :html))
```
`sprint` doesn't work too because of keyword argument
```julia
sprint(pretty_table, x, backend = :html)
```
So the only way is to use:
```julia
io = IOBuffer()
pretty_table(io, x, backend = :html)
str = String(resize!(io.data, io.size))
```

Is there a function that gives me the string directly? Writing and reading from io isn't that efficient.

**Comment by ronisbr** [comment]
Hi @aminya ,

Actually you can do this quite easy by using an `IOBuffer`:

```julia
julia> io = IOBuffer();

julia> pretty_table(io, [1 1 1; 1 1 1])

julia> str = String(take!(io))
"┌────────┬────────┬────────┐\n│ Col. 1 │ Col. 2 │ Col. 3 │\n├────────┼────────┼────────┤\n│      1 │      1 │      1 │\n│      1 │      1 │      1 │\n└────────┴────────┴────────┘\n"
```

Is it enough for you?

**Comment by ronisbr** [comment]
Oh, I just saw you figured out.

> Is there a function that gives me the string directly? Writing and reading from io isn't that efficient.

In fact, if I would code a function to return a string, that is exactly what I would do. There can be better ways, but they require big changes in how PrettyTables.jl work. Furthermore, since this is a package to print tables, such minor improvements should not make a noticeable difference. There is more important bottlenecks that can be improved.

**Comment by DhruvaSambrani** [comment]
I may be missing something, but isn't this a simple change from using the default io as stdout to allowing io to be nothing all the way until the final print in backends.text.print.jl where we check if an IO is provided or not and print it. We also do a cascading return through the whole stack to the main context. So we return string in all cases, but print only if IO is provided.

**Comment by ronisbr** [comment]
In fact that is not simple. I track the size of the display to make the `crop` work. Thus, I need an `io`. Second, when I started to code this package, I found that if I use a `string` and a lot of concatenation operations (like `str *= <something>`) to create the table, then the performance was very bad compared to the way we do today (create an `io` and print to it).

**Comment by DhruvaSambrani** [comment]
Right. But what I mean is to keep buf_io but remove io.
So all string building happens in a IOBuffer, but only the final output will be changed.
In the present method, you make a string from an IOBuffer to put into another IOBuffer. But if you just return the string, then there's one less IOBuffer read-write.
To be even more stingy, you can even just return the IOBuffer itself. For example 
```julia
pretty_io_buffer(...) :: IOBuffer
     #present code here except return buf_io through the myriad of helper function calls
end

pretty_string(...) :: String
     return String(take!(pretty_io(...)))
end

pretty_print(io, ...) :: Nothing
    #for backward compatibility
    print(io, pretty_string)
end
```
Also, you could have an optional IOBuffer param in pretty_io_buffer to fill into, which defaults to buf_io. I don't know how this will affect your printing logic though, as you may have a non empty IOBuffer sent in.

**Comment by DhruvaSambrani** [comment]
As for the best way to do String building in Julia is what you've already implemented in IOBuffer. [Here](https://discourse.julialang.org/t/string-builder-in-julia/17225/9)

**Comment by ronisbr** [comment]
> Right. But what I mean is to keep buf_io but remove io.
> So all string building happens in a IOBuffer, but only the final output will be changed.
> In the present method, you make a string from an IOBuffer to put into another IOBuffer. But if you just return the string, then there's one less IOBuffer read-write.
> To be even more stingy, you can even just return the IOBuffer itself. For example
> 
> ```julia
> pretty_io_buffer(...) :: IOBuffer
>      #present code here except return buf_io through the myriad of helper function calls
> end
> 
> pretty_string(...) :: String
>      return String(take!(pretty_io(...)))
> end
> 
> pretty_print(io, ...) :: Nothing
>     #for backward compatibility
>     print(io, pretty_string)
> end
> ```
> 
> Also, you could have an optional IOBuffer param in pretty_io_buffer to fill into, which defaults to buf_io. I don't know how this will affect your printing logic though, as you may have a non empty IOBuffer sent in.

I really thought this very confusing. The user probably will want the table into a string only during specific scenarios. The best way is to create a `pretty_table_to_str`

**Comment by ronisbr** [comment]
Much better is to define a new method with the signature: `pretty_table(::Type{String},...)`. Thus, a string can be returned by `pretty_table(String, ...)`.

**Comment by ronisbr** [comment]
Done! I should have done this before. It is now much easier to write the test functions.

```julia
julia> data = [1 2 3; 4 5 6];

julia> str = pretty_table(String, data, ["Column 1", "Column 2", "Column 3"]);

julia> print(str)
┌──────────┬──────────┬──────────┐
│ Column 1 │ Column 2 │ Column 3 │
├──────────┼──────────┼──────────┤
│        1 │        2 │        3 │
│        4 │        5 │        6 │
└──────────┴──────────┴──────────┘
```
