### ISSUE TITLE
suppress header

### ISSUE THREAD

**Issue by PaulSoderlind** [ronisbr/PrettyTables.jl#3]
what about supplying a convenience function for printing matrices (without headers and borders) 

`pretty_matrix(x) = pretty_table(x,fill("",size(x,2)),borderless)`

I bet some users would like it.

Btw. the manual could mention that `formatter=ft_print(fmt)` does not require fmt to be hardcoded. That's a nice feature (compared to, say, @sprintf)

**Comment by ronisbr** [comment]
Very good suggestion! It will be very easy to implement.

> Btw. the manual could mention that `formatter=ft_print(fmt)` does not require fmt to be hardcoded. That's a nice feature (compared to, say, @sprintf)

I think I did not understand what you said here. I am calling `@sprintf` in `ft_print` but using `@eval`.

**Comment by PaulSoderlind** [comment]
I meant that your package allows me to do
```
width = 5
prec  = 2
fmt = string("%",width,".",prec,"f")
```
which is very nice (and a bit like Formatting.jl). Worth pointing out.

**Comment by ronisbr** [comment]
Oh yes! Now I understand :) I will add this in the documentation.

**Comment by ronisbr** [comment]
Done! Now we have the `no header` keyword to suppress the header :) thanks for the suggestion. Can you please test before I tag the new version? I will add you suggestion to improve the documentation later.

**Comment by PaulSoderlind** [comment]
Works nicely in the new release.  (Sorry, I had no time to test earlier.)  Thanks
