### ISSUE TITLE
Add Matrix backend

### ISSUE THREAD

**Issue by DhruvaSambrani** [ronisbr/PrettyTables.jl#33]
Used to output the table as a mathematical matrix.

REPL - 
> The borders of `unicode`, but without the horizontal lines. Center align by default if possible.

```
┌                                   ┐
│      1    false      1.0        1 │
│      2     true      2.0        2 │
│      3    false      3.0        3 │
└                                   ┘
```

LaTeX  - 
```latex
$$ \left[
  \begin{array}{ c c }
     1 & 2 \\
     3 & 4
  \end{array} \right]
$$
```
[source](https://andy-roberts.net/writing/latex/mathematics_1)
HTML - [Here](http://jsfiddle.net/NQ6ww/38/)

**Comment by ronisbr** [comment]
Hi @DhruvaSambrani ,

As I pointed out in the PR, I did something very wrong and had to hard reset everything. However, I think we can discuss a little how can we implement this feature. I really like the idea to print matrices as you showed. However, adding right and left borders does not really fix everything.

I always wanted to change how the text table format is handle. I think the best was is to define a line as a string like this:

```julia
line = "├─┼┤"
```

with the characters to build the line. Then, we can add formats for the top line, header separation line, row line, and bottom line. With this, we will have a very good flexibility to create text formats as you proposed.

**Comment by DhruvaSambrani** [comment]
But internally, don't you need to again split it into the chars? And if we are going to do that anyway, might as well store them as a dictionary as we are doing it now. We could add another TextFormat constructor which splits it like how you said. We will still need different "border" elements though, as a column separator may not be the same as the border.

**Comment by ronisbr** [comment]
> But internally, don't you need to again split it into the chars?

Yes, we have two approaches here. First, we can use `string[1]`, `string[2]`, and so on. Or we can create a struct with a `convert`  definition to change the string to characters as we are using today.

I will try to implement something this weekend and then we can discuss :) If you have any better idea, please, let me know!

**Comment by DhruvaSambrani** [comment]
I don't personally like string[k] as it gets really difficult to extend it if necessary. Like rn, I just had to add another entry to the Dict and call accordingly. If we choose to add a char in-between, you'll need to re-index it all over again in all the locations. Instead, a `convert` function would help better.

**Comment by DhruvaSambrani** [comment]
Should I PR again? You can merge to a new branch and make your changes there, so that you can edit it to add the syntactic sugars

**Comment by ronisbr** [comment]
Hi @DhruvaSambrani 

I recently commit a breaking change to PrettyTables.jl. We now have a way to suppress drawing of vertical lines and this can be set in each format. Thus, the option `left_border` and `right_border` were no long necessary. Can you please test to see if I broke something in your workflow?

**Comment by waldyrious** [comment]
@ronisbr It would be nice if we could use actual bracket characters for the matrix backend. Unicode has [dedicated characters](https://en.wikipedia.org/wiki/Miscellaneous_Technical) for precisely this use case (I suggested using them for Julia's log messages in https://github.com/JuliaLang/julia/pull/33898).

In PrettyTables.jl it would look like this:

Before:
```
┌                     ┐
│ 1   false   1.0   1 │
│ 2    true   2.0   2 │
│ 3   false   3.0   3 │
└                     ┘
```
After:
```
⎡ 1   false   1.0   1 ⎤
⎜ 2    true   2.0   2 ⎥
⎣ 3   false   3.0   3 ⎦
```

I would propose this change as a PR myself, but I'm not sure how to implement it, since with the extended bracket characters the corners are not placed in a separate "row", as is the case with the current format, but rather inline with the first and last lines of actual content. Would this be possible with the current implementation?

**Comment by ronisbr** [comment]
> I would propose this change as a PR myself, but I'm not sure how to implement it, since with the extended bracket characters the corners are not placed in a separate "row", as is the case with the current format, but rather inline with the first and last lines of actual content. Would this be possible with the current implementation?

This is nice! However, it will be a "huge" change in the API. We need to check if it is the first line to be printed (of the last line) and change the printed chars. IMHO, the best way here is to create a new back-end dedicated to print matrix.

**Comment by waldyrious** [comment]
Yeah, I suspected it wouldn't fit well with the current system. 😅

Do you want me to open a new issue to track that change?

**Comment by ronisbr** [comment]
Yes, please!
