### ISSUE TITLE
Add vertical divisions in LaTeX

### ISSUE THREAD

**Issue by DhruvaSambrani** [ronisbr/PrettyTables.jl#35]
Add vertical separators in LaTeX backend formats.
#33 cannot be completely rectified until then.

**Comment by ronisbr** [comment]
@DhruvaSambrani hi!

Can you please remember me what should I do here? By vertical divisions, do you mean those `|` we add in the table description, like `cc|c|`?

**Comment by DhruvaSambrani** [comment]
I don't quite remember right now 😅 I think you can close this of no one else has an issue

**Comment by ronisbr** [comment]
Ok! Sorry for the time I took to go back to it :) Anyway, if it was those separators, we can now use the option `vlines`.
