### ISSUE TITLE
Support for schemaless tables?

### ISSUE THREAD

**Issue by mlhetland** [ronisbr/PrettyTables.jl#45]
It seems the support is halfway there, but not quite? In `_pretty_table_Tables`, we find the [following lines](https://github.com/ronisbr/PrettyTables.jl/blob/c1eb854e4ce890ae78604875601bbace96702088/src/print.jl#L457-L459):

```
data = Tables.matrix(table)

if sch == nothing
```

However, if the schema is `nothing` (the default), `Tables.matrix` won't work, as the [second thing it does](https://github.com/JuliaData/Tables.jl/blob/1c1e628f209e331db21aa705a707fcc22024ee87/src/matrix.jl#L68) is to access `sch.types` (which does not exist).

I guess `Tables.matrix` can't be used at all in this case (unless that itself is updated to use `Any` as column types when there is no schema, or something)…

As for the colum names: The body of the `if sch == nothing` clause constructs new column names, if they aren't supplied directly as an argument – but there's no need to do that, as `columnnames` is a required part of the `Tables.jl` interface (as opposed to `schema`). Slightly easier to access for `columnaccess` tables (as for `rowaccess` tables, you'd have to extract the first row to get the column names), but doable either way.

An alternative is to require `schema`, but in that case there's no need for the current code that tries to handle the no-schema condition.

**Comment by mlhetland** [comment]
Also, if I *do* define a schema for my table type, I have no choice in whether or not to include the types in the header, as the `header` argument is now ignored. (I'm thinking it should probably be used whether or not there is a scheme, if it is explicitly provided?)

**Comment by ronisbr** [comment]
Hum, very interesting! Nice catch.

You are 100% right. I think the right approach is to check if the Table is a row table or a column table and handle it correctly. The challenge here will be do something that decrease the cases in which a full copy will be necessary to make something compatible with PrettyTables low-level functions.

> Also, if I _do_ define a schema for my table type, I have no choice in whether or not to include the types in the header, as the `header` argument is now ignored. (I'm thinking it should probably be used whether or not there is a scheme, if it is explicitly provided?)

OK, this seems very logical. Let's see what I can do.

**Comment by mlhetland** [comment]
Awesome!

**Comment by ronisbr** [comment]
Hi @mlhetland !

Done, can you please test? Now, if a header is passed with something that complies with Tables.jl API, then this header will be used:

```julia
julia> using PrettyTables

julia> using DataFrames

julia> df = DataFrame(a = 1:1:10, b = 1:2.:20, c = Int32(1):Int32(3):Int32(30) );

julia> pretty_table(df)
┌───────┬─────────┬───────┐
│     a │       b │     c │
│ Int64 │ Float64 │ Int32 │
├───────┼─────────┼───────┤
│     1 │     1.0 │     1 │
│     2 │     3.0 │     4 │
│     3 │     5.0 │     7 │
│     4 │     7.0 │    10 │
│     5 │     9.0 │    13 │
│     6 │    11.0 │    16 │
│     7 │    13.0 │    19 │
│     8 │    15.0 │    22 │
│     9 │    17.0 │    25 │
│    10 │    19.0 │    28 │
└───────┴─────────┴───────┘

julia> pretty_table(df, ["1st", "2nd", "3rd"])
┌─────┬──────┬─────┐
│ 1st │  2nd │ 3rd │
├─────┼──────┼─────┤
│   1 │  1.0 │   1 │
│   2 │  3.0 │   4 │
│   3 │  5.0 │   7 │
│   4 │  7.0 │  10 │
│   5 │  9.0 │  13 │
│   6 │ 11.0 │  16 │
│   7 │ 13.0 │  19 │
│   8 │ 15.0 │  22 │
│   9 │ 17.0 │  25 │
│  10 │ 19.0 │  28 │
└─────┴──────┴─────┘
```

Moreover, if the schema is missing, then the column names is used:

```julia
julia> using Tables

julia> using PrettyTables

julia> data = Any[1    false      1.0     0x01 ;
                  2     true      2.0     0x02 ;
                  3    false      3.0     0x03 ;
                  4     true      4.0     0x04 ;
                  5    false      5.0     0x05 ;
                  6     true      6.0     0x06 ;];

julia> struct MyColumnTable{T <: AbstractMatrix}
           names::Vector{Symbol}
           lookup::Dict{Symbol, Int}
           matrix::T
       end;

julia> Tables.istable(::Type{<:MyColumnTable}) = true;

julia> names(m::MyColumnTable) = getfield(m, :names);

julia> mat(m::MyColumnTable) = getfield(m, :matrix);

julia> lookup(m::MyColumnTable) = getfield(m, :lookup);

julia> Tables.columnaccess(::Type{<:MyColumnTable}) = true;

julia> Tables.columns(m::MyColumnTable) = m;

julia> Tables.getcolumn(m::MyColumnTable, ::Type{T}, col::Int, nm::Symbol) where {T} = mat(m)[:, col];

julia> Tables.getcolumn(m::MyColumnTable, nm::Symbol) = mat(m)[:, lookup(m)[nm]];

julia> Tables.getcolumn(m::MyColumnTable, i::Int) = mat(m)[:, i];

julia> Tables.columnnames(m::MyColumnTable) = names(m);

julia> table = MyColumnTable([:a,:b,:c,:d],
                             Dict(:a => 1, :b => 2, :c => 3, :d => 4),
                             data);

julia> print(Tables.schema(table))
nothing
julia> result = pretty_table(table)
┌───┬───────┬─────┬───┐
│ a │     b │   c │ d │
├───┼───────┼─────┼───┤
│ 1 │ false │ 1.0 │ 1 │
│ 2 │  true │ 2.0 │ 2 │
│ 3 │ false │ 3.0 │ 3 │
│ 4 │  true │ 4.0 │ 4 │
│ 5 │ false │ 5.0 │ 5 │
│ 6 │  true │ 6.0 │ 6 │
└───┴───────┴─────┴───┘

```

**Comment by ronisbr** [comment]
By the way, I tried to design a method that avoids copying data. The low-level function of PrettyTables expects something that can be accessed using `data[i,j]`. Thus, I created auxiliary structures that mimics this behavior for tables that can be accessed by columns and by rows.

**Comment by mlhetland** [comment]
Excellent! Yes, at least for my use case it works perfectly, both without a schema and with schema + custom header. Thanks!
