### ISSUE TITLE
Export table to PDF/PNG

### ISSUE THREAD

**Issue by azev77** [ronisbr/PrettyTables.jl#50]
Hi and thanks for your package!
Is it possible to export a table to pdf/png etc?

**Comment by ronisbr** [comment]
Hi @azev77 !

Hum, I have no idea how can we directly export a table to a PNG/PDF. Any suggestions? However, you can export to LaTeX using the LaTeX back-end, and then export to PDF, for example.

**Comment by ronisbr** [comment]
I analyzed this further. Unfortunately, the solution would depend on a lot of external packages, because I would need to export to LaTeX ou HTML and then convert. I think this feature does not belong to this package. Maybe someone can create another package that glue those functionalities!
