### ISSUE TITLE
Make column_names of ColumnTable parametric

### ISSUE THREAD

**Issue by Tokazama** [ronisbr/PrettyTables.jl#52]
I have a table that gets stuck at [this line](https://github.com/ronisbr/PrettyTables.jl/blob/master/src/print.jl#L609) because `ColumnTable` only accepts a `Vector` for the column names. If `ColumnTable` was defined like this...

```julia
struct ColumnTable{T,V<:AbstractVector{Symbol}}
    table::T
    column_names::V
    size::Tuple{Int,Int}
end
```

...then you could still guarantee a vector like interface. What do you think?

**Comment by ronisbr** [comment]
Hum, can you please provide a minimum working example of the error?

**Comment by Tokazama** [comment]
It's because the table type I've made returns a vector that is `<:StaticArray`.

This is the error I get. 

`ERROR: MethodError: no method matching PrettyTables.ColumnTable(::AxisTable{Array{Int64,1},StaticArrays.SArray{Tuple{2},Array{Int64,1},1,2},SimpleAxis{Int64,Base.OneTo{Int64}},AxisIndices.StructAxes.StructAxis{NamedTuple
{(:a, :b),Tuple{Array{Int64,1},Array{Int64,1}}},2,Int64,OneToSRange{Int64,2}}}, ::StaticArrays.SizedArray{Tuple{2},Symbol,1,1}, ::Tuple{Int64,Int64})`

**Comment by ronisbr** [comment]
Hum, OK! I think this can be done.

Is it possible to create a very small example with a custom table type so that I can add in the test set?
