### ISSUE TITLE
Heatmap feature

### ISSUE THREAD

**Issue by juliohm** [ronisbr/PrettyTables.jl#55]
Thanks for this awesome package. I am trying to create a "heatmap" effect on the entries of the table. I can generate colorscales with Crayons like `cs = [Crayon(i) for i in 1:10]` and map each string entry in the table to one of these colors like `Dict(s .=> cs)`. However, to apply each color we need to create as many highlighters as colors and then pass them all to the table. Is there any other method to create this heatmap?

**Comment by ronisbr** [comment]
Hi @juliohm !

Thanks! I am glad it is being useful!

Indeed, it was necessary on old versions. After 0.9, you have the following `Highlighter` interface:

```julia
@with_kw struct Highlighter
    f::Function
    fd::Function = (h,data,i,j)->h.crayon

    # Private
    crayon::Crayon = Crayon()
end
```

where the function `f(data, i,j)::Bool` checks if the highlighter must be applied for the cell `(i,j)` of the table `data`. If it is true, then the function `fd(h, data,i,j)::Crayon` is called and must return the crayon for that cell.

Here is an example using [ColorScheme.jl](https://github.com/JuliaGraphics/ColorSchemes.jl)

```Julia
julia> using PrettyTables

julia> using ColorSchemes

julia> data = [ sind(x)*cosd(y) for x in 0:10:180, y in 0:10:180 ]

julia> hl = Highlighter((data,i,j)->true,
                        (h,data,i,j)->begin
                             color = get(colorschemes[:coolwarm], data[i,j], (-1,1))
                             return Crayon(foreground = (round(Int,color.r*255),
                                                         round(Int,color.g*255),
                                                         round(Int,color.b*255)))
                         end)

julia> pretty_table(data, ["x = $(x)°" for x = 0:10:180],
                    row_names = ["y = $(y)°" for y = 0:10:180],
                    highlighters = hl,
                    formatters = ft_printf("%.2f"))
```

that leads to:

<img width="1678" alt="ex_00015" src="https://user-images.githubusercontent.com/1068295/82613212-21f28700-9b9b-11ea-8b20-21a2b1290580.png">

Thus, I think you can easily modify the highlighter `hl` in that snippet to return the correct crayon based on the data you have in each cell.

**Comment by juliohm** [comment]
Awesome @ronisbr ! Will do it locally, thanks for the quick reply :)

**Comment by ronisbr** [comment]
Good, please, tell me if this worked well!

**Comment by juliohm** [comment]
Works beautifully @ronisbr , thanks again for the package, super useful 👌
