### ISSUE TITLE
LaTeX headers: no textbf?

### ISSUE THREAD

**Issue by dpo** [ronisbr/PrettyTables.jl#59]
Is there a way to not wrap the table header in `\textbf{}` in the LaTeX backend? When we want to use math in the header, some items are bold and some not because `\textbf{\(f\)}` doesn't display "f" in bold math.

Example from the documentation:
```julia
julia> header = ["\\(t\\)"   "\\(a\\)"    "Velocity" "Distance";
                     "[s]"  "[m/s\$^2\$]"    "[m/s]"      "[m]"];

julia> pretty_table(data, header, backend = :latex)
```

![Screen Shot 2020-06-04 at 17 09 24](https://user-images.githubusercontent.com/38760/83810440-254f3d80-a686-11ea-986d-43bce17f9820.png)

**Comment by ronisbr** [comment]
Yes! You just need to create a custom table format:

```julia
tf = LatexTableFormat(latex_deafult; header_envs = [])
```

Then use it in the option `tf` of `pretty_table`.

Maybe I let this option to be available without creating a new table format before stabilizing the API.

**Comment by dpo** [comment]
Yay! Thank you!
