### ISSUE TITLE
Thoughts on accepting `Dict` as input?

### ISSUE THREAD

**Issue by 00vareladavid** [ronisbr/PrettyTables.jl#6]
First of all: awesome package! The less often I have to leave my terminal, the better.

A reasonable way to represent a table is `Dict{ID, Dict{Keys, Values}}`. I hacked something together for my use case, but it might be nice for `PrettyTables` to support this natively.

**Comment by ronisbr** [comment]
Hi @00vareladavid ,

With my latest commit, we can now print dictionaries. I know that it is now what you initially proposed, but I really did not understand your use case. Feel free to reopen if desired.
