### ISSUE TITLE
New version release (with overwrite functionality)?

### ISSUE THREAD

**Issue by ianshmean** [ronisbr/PrettyTables.jl#60]
I've been using the overwrite functionality in another package. I'd be great to get a release out with it

**Comment by Octogonapus** [comment]
I would also like to see this

**Comment by ronisbr** [comment]
Ouch! Sorry about that, I completely forgot to tag a version. I will do this as soon as I have access to my computer!

**Comment by ianshmean** [comment]
Thanks!
