### ISSUE TITLE
Add a table title?

### ISSUE THREAD

**Issue by tlienart** [ronisbr/PrettyTables.jl#62]
Hello, 

Thanks for your package, very useful! I was wondering whether it'd be possible to add a `tilte=...` kwarg to `pretty_table` to have the table displayed with a title; that's convenient  when displaying multiple tables in a sequence for different `combine/groupby`. 

Thanks!

**Comment by ronisbr** [comment]
Hi @tlienart !

Yes, this has been a very long request (#32). I will close as a duplicated but, please, can you comment there to provide information how do you imagine that this can be implemented, especially for the Text backend?
