### ISSUE TITLE
Support for rich cell content using Markdown

### ISSUE THREAD

**Issue by NicholasWMRitchie** [ronisbr/PrettyTables.jl#64]
With very minor changes to the output code, it is possible to support rich output of Markdown.MD objects as I show in this image:

![image](https://user-images.githubusercontent.com/8323528/89210221-b743cb80-d58d-11ea-960c-c2af9d44c862.png)

`repr(MIME("text/html"), data_ij)` converts the markdown to HTML (similar for "text/plain" and "text/latex").  It makes sense to handle markdown differently because it is uniquely translatable into other common output formats.

With a couple of lines of code, it is possible to add easy support for HTML links, simple text formatting and image outputs.
This would greatly enhance the utility of the tables generated by PrettyTables.   One such use case is generating tables for a static HTML page.  Often it is desirable to be able to include images and links in such a table.  Currently, it isn't possible (I think.)

I've submitted a similar idea to DataFrames but since there is a suggestion to move to PrettyTables for output, I thought I'd also submit the idea here.

I submitted pull request #63 with some prototype code.

**Comment by ronisbr** [comment]
Hi @NicholasWMRitchie 

After you PR, I did some major modifications to Markdown. Now, PrettyTables.jl can render Markdown inside a table cell in Text back-end. See this example:

```julia
julia> a = md"""
       # Markdown

       This is a **Markdown** example.

       !!! note

           This is a note.

       This is a URL: [PrettyTables.jl](https://github.com/ronisbr/PrettyTables.jl)
       """;

julia> b = md"""
       This _**is a bold text that will wrap inside a cell**_
       """;

julia> data = [1 a; 2 b];

julia> pretty_table(data, linebreaks = true, hlines = :all, columns_width = [-1,40])
```

<img width="431" alt="Captura de Tela 2020-09-01 às 22 49 36" src="https://user-images.githubusercontent.com/1068295/91922970-9e6e2900-eca5-11ea-87e3-b4f2e51fd111.png">

However, this required a very complicated logic. The major problem was to copy the text format from one line to another when the line is wrapped. Can you help me to test?
