### ISSUE TITLE
Alighment for Headers to be different than data column

### ISSUE THREAD

**Issue by StevenSiew** [ronisbr/PrettyTables.jl#66]
I have a need where I want the headers to be align with "center alignment" but the data columns to be alignment with ":l" or "left justified"
I gave some thoughts about this and I came up with this suggestion

    # data columns are all left aligned
    alignment=:l
    # header for data columns are aligned the same as data columns
    headeralignment=:s      # DEFAULT

    # data columns are all left aligned
    alignment=:l
    # header for data columns are center aligned 
    headeralignment=:c

**Comment by ronisbr** [comment]
Hi @StevenSiew 

I agree! We need something like that.

I propose something similar to what we have in the table body:

* `header_alignment`: A vector of symbols indicating the alignment of the header. It can be `:l`, `:c`, or `:r`. If it is anything else, then the alignment of the column will be used.
* `header_cell_alignment`: A `Dict` just like the `cell_alingment` to override the alignment of a specific cell in the header. In this case, we can change the alignment of the sub-headers, for example.

Do you agree?

**Comment by StevenSiew** [comment]
Yes I do agree with your suggestion.

**Comment by ronisbr** [comment]
Done! Can you please test?

```julia
julia> pretty_table(ones(3,4), ["A" "B" "C" "D"; "a" "b" "c" "d"],
                    alignment = :l,
                    columns_width = 9,
                    header_alignment = :c,
                    header_cell_alignment = Dict( (2,1) => :l,
                                                  (2,2) => :r,
                                                  (2,4) => :r))
┌───────────┬───────────┬───────────┬───────────┐
│     A     │     B     │     C     │     D     │
│ a         │         b │     c     │         d │
├───────────┼───────────┼───────────┼───────────┤
│ 1.0       │ 1.0       │ 1.0       │ 1.0       │
│ 1.0       │ 1.0       │ 1.0       │ 1.0       │
│ 1.0       │ 1.0       │ 1.0       │ 1.0       │
└───────────┴───────────┴───────────┴───────────┘
```

Should be working with all backends.
