### ISSUE TITLE
row_name_crayon does not work for me

### ISSUE THREAD

**Issue by alusiani** [ronisbr/PrettyTables.jl#68]
I am using PrettyTables v0.9.1 and I am unable to highlight row names.

```julia
pretty_table([1 2; 3 4], ["a", "b"], row_names=["r", "q"], row_name_crayon=crayon"blue", header_crayon=crayon"blue")
```

works for the header, both in a term and in jupyter, which shows up in blue, but does not work for the row names, which are shown in plain style. The same happens using crayon"bold".

**Comment by ronisbr** [comment]
Hi @alusiani ,

Sorry for the late response. Yes, `row_name_crayon` is applied only to the titles. I will do the following:

* `row_name_crayon` will be applied to the names.
* `row_name_title_crayon` will be applied to the title of the columns.

This seems much more consistent.

**Comment by alusiani** [comment]
> Hi @alusiani ,
> 
> Sorry for the late response. Yes, `row_name_crayon` is applied only to the titles. I will do the following:
> 
> * `row_name_crayon` will be applied to the names.
> * `row_name_title_crayon` will be applied to the title of the columns.
> 
> This seems much more consistent.

Yes, that would be the most appropriate solutiom, I agree.

Thanks for the feedback and for the nice package,
--
Alberto

**Comment by ronisbr** [comment]
Sorry for the delay, but it should be fixed in `master`.

```julia
julia> pretty_table([1 2; 3 4], ["a", "b"], row_names=["r", "q"], row_name_column_title = "x", row_name_crayon=crayon"bold blue", header_crayon=crayon"bold blue", row_name_header_crayon = crayon"bold yellow")
```

<img width="105" alt="Captura de Tela 2020-08-29 às 22 07 49" src="https://user-images.githubusercontent.com/1068295/91648929-3b318c00-ea44-11ea-8668-3ff2dcf4330e.png">

**Comment by alusiani** [comment]
> Sorry for the delay, but it should be fixed in `master`.
> 
> ```julia
> julia> pretty_table([1 2; 3 4], ["a", "b"], row_names=["r", "q"], row_name_column_title = "x", row_name_crayon=crayon"bold blue", header_crayon=crayon"bold blue", row_name_header_crayon = crayon"bold yellow")
> ```
> 
> <img alt="Captura de Tela 2020-08-29 às 22 07 49" width="105" src="https://user-images.githubusercontent.com/1068295/91648929-3b318c00-ea44-11ea-8668-3ff2dcf4330e.png">

Thanks again! It works for me.
\--
Alberto Lusiani
