### ISSUE TITLE
LaTeX backend does not honor row_names

### ISSUE THREAD

**Issue by alusiani** [ronisbr/PrettyTables.jl#69]
Hi,

row_names are not included in the LaTeX output in this example
```julia
pretty_table([1 2; 3 4], ["c1", "c2"], row_names=["r1", "r2"], backend = :latex)
```
I am using PrettyTables v0.9.1.
Row names are included when not specifying "backend = :latex"

Best wishes!
\--
Alberto

**Comment by BriceonWiley** [comment]
Has there been any progress made with this issue?

**Comment by ronisbr** [comment]
Hi @BriceonWiley 

No! I have been busy preparing the Text backend to be used in DataFrames. Now that everything was done, I can focus on the two other backends.

**Comment by BriceonWiley** [comment]
Sounds great! Can't wait to see it!

**Comment by ronisbr** [comment]
Done! Sorry for taking so long :)

**Comment by alusiani** [comment]
> Done! Sorry for taking so long :)

Well done! WIll test it when I have a moment.
