### ISSUE TITLE
Float alignment to decimal dot

### ISSUE THREAD

**Issue by dav2017** [ronisbr/PrettyTables.jl#75]
Thanks for this really nice package.
I would suggest a useful alignment for float numbers would be  of this kind:

```
-11.2
  1.34
 12.45
```

Maybe I missed how to get it through PrettyTables, but I had to write my own function to process each float number column (converting to string and padding) before passing it to pretty_table().

Best
   Davide

**Comment by ronisbr** [comment]
Hi @dav2017 !

Thanks, I am glad it is being useful!

To really solve this problem, we need to parse the entire row before applying the alignment. This is not good due to the way PrettyTables.jl render the data. We will need to create something specific for this use case, introducing too much complications. However, there is two good workarounds.

1. Use the formatter `ft_printf` like this:

```julia
julia> data = [-11.2; 1.34; 12.45; 1.3324; +55.42; 1002.23];

julia> pretty_table(data, formatters = ft_printf("%3.4f"))
┌───────────┐
│    Col. 1 │
├───────────┤
│  -11.2000 │
│    1.3400 │
│   12.4500 │
│    1.3324 │
│   55.4200 │
│ 1002.2300 │
└───────────┘
```

However, you get trailing zeros.

2. Use a second formatter to remove those trailing zeros:

```julia
julia> function replace_trailing_zeros(v)
           old_size = textwidth(v)
           v = rstrip(v, '0')
           new_size = textwidth(v)
           return v * " "^(old_size - new_size)
       end

julia> pretty_table(data, formatters = (ft_printf("%3.4f"), (v,i,j)->replace_trailing_zeros(v)))
┌───────────┐
│    Col. 1 │
├───────────┤
│  -11.2    │
│    1.34   │
│   12.45   │
│    1.3324 │
│   55.42   │
│ 1002.23   │
└───────────┘
```

The only "downside" of those two methods is that you will need to control the field size.

**Comment by dav2017** [comment]
Thanks @ronisbr, for this useful workaround, certainly I will use it.
A minor drawback is that it can only be used with `alignment=:r`.

What a came to was pre-processing the matrix/d.f. through a function which returns a padded string vector, applying it to each float number column:

```
function aligndec(x::Array{Float64,1})
    # Convert values to strings
    stringVect = map(v -> "$v", x)
    # Split units and decimal digits
    #units = [split.(stringVect, ".")[i][1] for i in 1:length(x)]
    #decimals = [split.(stringVect, ".")[i][2] for i in 1:length(x)]
    units = map(s -> split.(s, ".")[1], stringVect)
    decimals = map(s -> split.(s, ".")[2], stringVect)

    # Calculate number of spaces to pad...
    # ... units...
    len = length.(units)
    uPad = repeat.(' ', maximum(len) .- len)
    # ... and digits
    len = length.(decimals)
    dPad = repeat.(' ', maximum(len) .- len)

    # returns a string vector with padded strings
    return uPad .* units .* '.' .* decimals .* dPad
end
```

This requires extra steps (and so it is far from optimal), but allows the use also of `:l` and `:c` alignments.

**Comment by ronisbr** [comment]
Yes, I see you point. However, since all those numbers will be aligned with the same field size, will the column alignment matter?

**Comment by dav2017** [comment]
Well, it may be relevant for other, not float number, columns in the same table, and for headers.

**Comment by ronisbr** [comment]
I see, however this kind of feature would require to process the entire table (the part that will be printed) and then do the alignment. In PrettyTables, you have a formatter that can change the output based on the value of the cell. Anything requiring more information than this should be processed before printing. Changing this assumption would required an enormous amount of work or a very strange API specific for this use case. Hence, I think, IMHO, that this feature does not fit well in PrettyTables. At least not within a midterm horizon.

**Comment by ronisbr** [comment]
Hi @dav2017 !

I think you will be interested in the new code I just pushed to `master`. Now we can define a regex to align the elements in a column. Hence, what you wanted can now be accomplished very easily:

```julia
julia> data = [-11.2
         1.34
        12.45];

julia> pretty_table(data, ["This is a big header"], column_alignment_regex = Dict(1 => r"\."))
┌──────────────────────┐
│ This is a big header │
├──────────────────────┤
│               -11.2  │
│                 1.34 │
│                12.45 │
└──────────────────────┘

julia> pretty_table(data, ["This is a big header"], column_alignment_regex = Dict(1 => r"\."), alignment = :c)
┌──────────────────────┐
│ This is a big header │
├──────────────────────┤
│        -11.2         │
│          1.34        │
│         12.45        │
└──────────────────────┘

julia> pretty_table(data, ["This is a big header"], column_alignment_regex = Dict(1 => r"\."), alignment = :l)
┌──────────────────────┐
│ This is a big header │
├──────────────────────┤
│ -11.2                │
│   1.34               │
│  12.45               │
└──────────────────────┘
```

**Comment by dav2017** [comment]
That's great! Thank you.

   Davide


Dec 22, 2020, 11:52 by notifications@github.com:

**Comment by ronisbr** [comment]
I just change the name of the keyword to `alignment_anchor_regex` in case you want to test :D
