### ISSUE TITLE
Display width in IJulia (Jupyter): how to avoid truncation?

### ISSUE THREAD

**Issue by ShuhuaGao** [ronisbr/PrettyTables.jl#76]
PrettyTables work perfectly in terminal (or REPL):
![Snipaste_2020-09-18_19-46-16](https://user-images.githubusercontent.com/20141984/93594004-a4734200-f9e7-11ea-9190-6bcc11fcf8c8.png)
However, the same code can only print a partial table in IJulia (aka, Jupyter notebook):
![Snipaste_2020-09-18_19-47-46](https://user-images.githubusercontent.com/20141984/93594123-d684a400-f9e7-11ea-99b4-6e87d4354412.png)
Though the cell is wide enough for the table, there is still truncation followed by an ellipsis. Is it a limitation of IJulia or PrettyTable? What shall we do to fix it if possible?

**Comment by ronisbr** [comment]
Hi @ShuhuaGao 

I think that IJulia is defining a virtual screen limit. You can avoid cropping by passing the option `crop = :none`.

**Comment by ShuhuaGao** [comment]
Hi, @ronisbr . Thank you for your quick response. Yes, the keyword argument `crop = :none` worked.
![Snipaste_2020-09-18_20-03-44](https://user-images.githubusercontent.com/20141984/93595302-151b5e00-f9ea-11ea-82c2-8bfe0c4d95d1.png)
I just noticed the option in [Cropping](https://ronisbr.github.io/PrettyTables.jl/stable/man/text_backend/#Cropping-1) part of the documentation. Perhaps it may be better emphasized for especially IJulia in the [Usage](https://ronisbr.github.io/PrettyTables.jl/stable/man/usage/) part since the keyword `crop` is not mentioned there.

**Comment by ronisbr** [comment]
Good! I will add the documentation.
