### ISSUE TITLE
Possible to fix 1.6-DEV issue?

### ISSUE THREAD

**Issue by goedman** [ronisbr/PrettyTables.jl#77]
Hi,

Any chance PrettyTables can be updated to work on Julia 1.6-DEV? Through MCMCChains is is used in many of the test scripts in the StanJulia and StatisticalRethinkingJulia set of packages.

Thanks, Rob

**Comment by ronisbr** [comment]
Hi @goedman !

The only problem I am aware of that is related to Formatting.jl (https://github.com/JuliaIO/Formatting.jl/issues/87). I think this is the only issue that is leading to test failures in 1.6-DEV. The bug was closed, but a new version was not released yet.

**Comment by goedman** [comment]
Thank you! Master version of Formatting.jl indeed solves it.
