### ISSUE TITLE
New tagged release?

### ISSUE THREAD

**Issue by ali-ramadhan** [ronisbr/PrettyTables.jl#78]
Would it be possible to tag a new release? Hoping to use the new `title` kwarg and would be better to depend on a tagged release rather than on master (for stability).

Thanks so much! Awesome package by the way.

**Comment by ronisbr** [comment]
Hi @ali-ramadhan 

> Would it be possible to tag a new release? Hoping to use the new `title` kwarg and would be better to depend on a tagged release rather than on master (for stability).

Sorry about the delay. We are in the middle of the process to turn PrettyTables the default backend of DataFrames.jl (https://github.com/JuliaData/DataFrames.jl/pull/2429). Hence, the next release will be the 1.0 with a stable API. I just need some more time to check if there are any rough edges before the next release. Maybe I can do this by the weekend :)

> 
> Thanks so much! Awesome package by the way.

Nice! I am glad it is being useful.

**Comment by ali-ramadhan** [comment]
Thanks for the reply @ronisbr. That's great, I'm happy to wait. Looking forward to v1.0!

Feel free to close this issue now (or when v1.0 is tagged/released).

**Comment by ronisbr** [comment]
Done! v0.10.0 should be tagged very soon. I decided to tag this version before v1.0 so that we have time to fix bug and adapt the API.
