### ISSUE TITLE
Parameters.jl dep?

### ISSUE THREAD

**Issue by rafaqz** [ronisbr/PrettyTables.jl#79]
I'm wondering if this dependency is necessary, as it brings in 3 package dependencies in total. And this package, being awesome, is becoming a key dependency for everything.

Could `Base.@kwdef` be used instead of `@with_kw` ?

**Comment by ronisbr** [comment]
Hi @rafaqz ,

It is a little shameful, but I have never used `Base.@kwdef` 😅. I always used Parameters for those kind of things. I will analyze to check the benefits. This is not the first time I have been asked to do this.

**Comment by rafaqz** [comment]
No problem! Parameters.jl does a lot more things, but for just keyword constructors `Base.@kwdef` should be ok? (but I don't really know I hardly use it either!)

I'm using PrettyPrint.jl in https://github.com/rafaqz/ModelParameters.jl. But it's just a library so I'm trying to keep the weight down - and Parameters.jl contributes 30% of the deps

**Comment by ronisbr** [comment]
Yes, you have a good point. The good side of Parameters is to be able to create objects that copy the information from another, like:

```julia
table_format = TextFormat(ascii_dots, hlines = :none)
```

Then, all the fields will be equal `ascii_dots` except `hlines`. However, this seems to be a very specific case.

**Comment by rafaqz** [comment]
That's also very surprising for someone who doesn't know that

**Comment by ronisbr** [comment]
We have a trade-off here:

1. Using `@kwdef`, I loose the `@unpack` and I will have to write a lot of variables 😅 This is OK since I need to do this only once.
2. The gain as I mentioned before in PrettyTables.jl is only when defining a new Table Format. This seems very specific and the user can just copy and paste the code and do the modifications.

**Comment by ronisbr** [comment]
@rafaqz done! In fact, the usage of Parameters.jl in this package was not necessary at all. I removed it from the dependencies and the loading time dropped almost 30%.

**Comment by rafaqz** [comment]
Thanks that's great! It's a LOT of load time saved collectively for everyone who will be using this.
