### ISSUE TITLE
Change tf_markdown to adhere to Julia Markdown's Syntax of alignment

### ISSUE THREAD

**Issue by DhruvaSambrani** [ronisbr/PrettyTables.jl#82]
Or add new `tf_jlmd`

https://docs.julialang.org/en/v1/stdlib/Markdown/#Tables

**Comment by ronisbr** [comment]
Hi @DhruvaSambrani 

Yes, we need a backend for markdown derived from the text backend. This has already been requested here #67 . Hence, I will close as duplicate.
