### ISSUE TITLE
Latex tables wrapped in tabular environment

### ISSUE THREAD

**Issue by pdeffebach** [ronisbr/PrettyTables.jl#84]
I noticed the changelog that now latex tables are wrapped in a `table` environment. 

This broke my workflow, since I usually want to define the caption inside the latex document and do 

```
\begin{table}
    \caption{This is my caption}
    \label{lab}
    \input{../out/tables/mytable.tex} # starts with \begin{tabular}
\end{table}
```

It doesn't look like there is an option to revert to the old behavior, right? It would be great if this were a keyword argument, like it is in other table packages in other languages. 

Would you be okay with a PR for this?

**Comment by ronisbr** [comment]
Ouch, sorry about that 😊

Yes, this seems necessary!
