### ISSUE TITLE
ft_printf() not printing in fixed width

### ISSUE THREAD

**Issue by pgbarletta** [ronisbr/PrettyTables.jl#88]
Hello!
I've been fighting with this and finally ran out of ideas, so I think it might be an actual issue.

This is my function, taken from the manual:
```
open("salida", "w") do f
        pretty_table(f, m, tf=tf_borderless, noheader=true, formatters=ft_printf("% 14.4E"))
    end
```
I've tried with several variations but they all ran into the same problems:

1. The output width always ends up being unnecessarily bigger than the minimum required. In this case I'm asking for 14 characters and getting 17.
2. The first column is missing 1 padding character. So in this example the first column is 16 characters wide, and the rest of the columns are 17 characters wide.

I think this is bad interaction with the another option `tf=tf_borderless`. When I remove that, each column gets 4 blank leading padding spaces, which is good.

Thanks for any help.

This is a [piece](https://gist.github.com/pgbarletta/360040302c9874dc91b9356366f00c93) of the output file

edit: I mean, it's like the file was printed with borders, formatted, and then had the borders removed. If you do that, every column but the first one will have an extra leading padding character that comes from the space between the last character of the previous column and its left border:

```
│ -6.9827E-03 │ -1.2060E-02
------------------ ^
                       this right side padding character from the 1st column will turn into a left side padding character for the 2nd one.
```
Well, Github's markdown code is not fixed width so the caret character is pointing at the wrong position :/. It has to be copied and pasted elsewhere to see what I mean.

**Comment by ronisbr** [comment]
Hi @pgbarletta 

All columns in PrettyTables.jl will have a padding character before and after the text. This cannot be changed. The additional whitespaces you are seen is because `tf_borderless` has invisible borders (maybe the name selection was not good).

In this case, I think you need to pass the option `vlines = :none`:

```julia
julia> a = rand(3,3)
3×3 Array{Float64,2}:
 0.198986  0.118664  0.474904
 0.560208  0.348097  0.663822
 0.646378  0.812918  0.532486

julia> pretty_table(a, tf = tf_borderless, noheader = true, formatters=ft_printf("% 14.4E"))
      1.9899E-01       1.1866E-01       4.7490E-01
      5.6021E-01       3.4810E-01       6.6382E-01
      6.4638E-01       8.1292E-01       5.3249E-01

julia> pretty_table(a, tf = tf_borderless, noheader = true, formatters=ft_printf("% 14.4E"), vlines = :none)
     1.9899E-01      1.1866E-01      4.7490E-01
     5.6021E-01      3.4810E-01      6.6382E-01
     6.4638E-01      8.1292E-01      5.3249E-01

julia>
```

All the fields will have the same size if you consider that every cell has a padding character before and after the printed text (except for the last column in a row because I do remove trailing spaces).

**Comment by pgbarletta** [comment]
That's it! Thank you so much!
