### ISSUE TITLE
Formatter example from the manual does not work

### ISSUE THREAD

**Issue by bkamins** [ronisbr/PrettyTables.jl#91]
```
julia> using PrettyTables

julia> data = Any[ f(a) for a = 0:30:90, f in (sind,cosd,tand)];

julia> formatter = Dict(0 => (v,i) -> round(v,digits=3));

julia> pretty_table(data; formatter=formatter)
ERROR: MethodError: no method matching _pt_text(::IOContext{Base.TTY}, ::PrettyTables.PrintInfo; formatter=Dict(0 => var"#1#2"()))
```

**Comment by ronisbr** [comment]
Hi @bkamins !

This is a very old API that was replaced with:

```julia
julia> data = Any[ f(a) for a = 0:30:90, f in (sind,cosd,tand)];

julia> formatter = (v,i,j) -> round(v, digits=3);

julia> pretty_table(data; formatters = formatter)
```

The manual seems updated here, where did you find this example?

**Comment by bkamins** [comment]
Ah - now I see that I was directed to an old version of the manual. Sorry for mixing up.

Probably at some point you could do something like we did in https://github.com/JuliaData/DataFrames.jl/pull/2452 in DataFrames.jl to limit the risk of such problems. Thank you!
