### ISSUE TITLE
Simplex tableau

### ISSUE THREAD

**Issue by fusion809** [ronisbr/PrettyTables.jl#92]
Hi,

I wanted to generate formatted simplex tableaux in Julia and your package seemed the most suitable for this task. Then when I looked at the example in the README I realized the distinction between tables and tableaux may prevent me from using this package for that purpose. Is there a way of drawing tableaux like those shown here:

![Screenshot_20201115_183056](https://user-images.githubusercontent.com/4717341/99180322-ea8f1c80-2770-11eb-9180-df7e9eeb0128.png)

using this package?

Thanks for your time.

**Comment by ronisbr** [comment]
Hi @fusion809 !

Unfortunately, those kind of tables are very advanced. The LaTeX backend are still very immature even considering "normal" tables. I am afraid that it will take very long to add support for such things in PrettyTables.jl.

**Comment by fusion809** [comment]
Thanks for letting me know.
