### ISSUE TITLE
Use another color than red for "$n rows omitted"

### ISSUE THREAD

**Issue by nalimilan** [ronisbr/PrettyTables.jl#94]
I suggest using a different color than red to print "$n rows omitted" and "$n colors omitted". It seems to me that the convention is to use red only to indicate errors, and these red parts in the output catch the eye while they are not the most important information in the printed table.

I'm not sure what color would be best. In the Logging stdlib module, red is for errors, yellow for warnings, and blue for infos. In dplyr, tibbles print the number of omitted rows/columns in grey (but the size of the table is also printed in grey).

Cc: @bkamins

**Comment by bkamins** [comment]
I would print it in the same color as `Info` in `@info`.

**Comment by ronisbr** [comment]
Good! I will do this.

**Comment by ronisbr** [comment]
`@info` uses cyan and bold. I do not think we should use bold text here. What do you think?

Cyan and bold

![Captura de Tela 2020-11-22 às 11 20 02](https://user-images.githubusercontent.com/1068295/99906219-ab9f2080-2cb4-11eb-84c6-994ad0f7c144.png)

Cyan

![Captura de Tela 2020-11-22 às 11 20 30](https://user-images.githubusercontent.com/1068295/99906226-bbb70000-2cb4-11eb-98cc-dbe3bcb4993d.png)

**Comment by bkamins** [comment]
I meant only colour. I would not use bold.

**Comment by nalimilan** [comment]
I agree the second one (without bold) looks best. It shouldn't catch the eye too much as it will be printed very often without indicating anything abnormal happens.

**Comment by ronisbr** [comment]
Done! I think we need to update DataFrames tests before the next release. How can we do? I tag a new version of PrettyTables and then update?

**Comment by bkamins** [comment]
I think it is enough. Alternatively in DataFrames.jl you could write conditional tests depending on the version of PrettyTables.jl, but I think in this case it is not needed.
